### ISSUE TITLE
scroll problem on forms/regular.html

### ISSUE THREAD

**Issue by sorinr** [creativetimofficial/ct-material-dashboard-pro#1]
When scrolling down some elements on page content are scrolling up and others remain fixed and after some amount of scrolling they fade out.

Other pages in forms are working as supposed to.

Noticed this behavior on chrome Version 53.0.2785.116 (64-bit) on linux mint.

![screenshot from 2016-11-09 08-09-47](https://cloud.githubusercontent.com/assets/8637239/20128850/1734bc74-a654-11e6-822c-c3092b704704.png)
![screenshot from 2016-11-09 08-11-59](https://cloud.githubusercontent.com/assets/8637239/20128869/42986cf8-a654-11e6-88e7-80daae779579.png)

**Comment by alexandru-paduraru** [comment]
@sorinr thank you for the information. We've checked and it looks like the PerfectScrollbar library is creating those issues. We are working on an update (v1.0.1) that should come in 1-2 days to fix this issue and other small bugs.

Best,
Alex

**Comment by sorinr** [comment]
You are welcome Alex. I confess, I'm not a big fan of BS, but  I like your work and I'll always look up to receive info on your new projects. How about some flexbox versions of your projects?

Keep up the good job.

Sorin

**Comment by alexandru-paduraru** [comment]
@sorinr thank you for the kind words, glad that you like our products. We started to migrate our most famous UI kit: http://demos.creative-tim.com/get-shit-done/index.html to BS4 which will have flexbox, then we will migrate also the other products to BS4. 

Send us an email with your account and we will make sure you will see our new products before we release them :D

Best,
Alex
