### ISSUE TITLE
selectpicker does not scroll with the mouse

### ISSUE THREAD

**Issue by khrystyan88** [creativetimofficial/ct-material-dashboard-pro#100]
How can I enable so selectpicker can scroll with the mouse

![image](https://user-images.githubusercontent.com/27446663/35297135-1f1ab3f0-004c-11e8-9ede-d0066ef182ea.png)

**Comment by khrystyan88** [comment]
When I use select2, it works perfect


when I use select2, it works perfect, however with select2 I still can not turn off the search input


![image](https://user-images.githubusercontent.com/27446663/35297257-726b6e64-004c-11e8-862a-9fc711109e2f.png)

**Comment by dragosct10** [comment]
Hi, @khrystyan88! Sorry for the late response and thank you for using our product. Please, can you tell us on which browser did you test this? Regards, Dragos

**Comment by killer3dfx** [comment]
Hello, I have the same issue, tested in Chrome, Firefox and IE11.
