### ISSUE TITLE
Change width when sidebar toggles

### ISSUE THREAD

**Issue by jkrassman** [creativetimofficial/ct-material-dashboard-pro#101]
Hi,

I would like the navbar to do the automatic toggle when the screen is smaller then the default values, where in the css do I do that change?

Regards, Joakim

**Comment by jkrassman** [comment]
Or is it possible to disable that function?

**Comment by alexandru-paduraru** [comment]
@jkrassman thank you for using our product and sorry for the late response. Can you please give us more detail about what you want to achieve? I didn't really understand that.

Best,
Alex
