### ISSUE TITLE
Reinitialisation of custom checkboxes and radio buttons retrieved via AJAX

### ISSUE THREAD

**Issue by aky017** [creativetimofficial/ct-material-dashboard-pro#103]
Hello, can you please help me: I have Material Dashboard Pro and I can not figure out how to reinitialise custom checkboxes and radio buttons after retrieved them via AJAX.

**Comment by alexandru-paduraru** [comment]
@aky017 thank you for using our product and sorry for the late response, please check this library: https://github.com/FezVrasta/bootstrap-material-design/tree/v3#arrivejs-support
