### ISSUE TITLE
Sidebar closing when clicked

### ISSUE THREAD

**Issue by marcelomirandasilva** [creativetimofficial/ct-material-dashboard-pro#104]
In the sidebar when I click on a submenu item it performs the desired action but does close the menu. 
I would like it to remain showing the option that was selected. 

How to make it?

**Comment by dragosct10** [comment]
Hi, @marcelomirandasilva! Thank you for using our product. I understand what you want, but if you will do this in the responsive mode if the sidebar will remain open you can't see the main-panel displayed with the actions that you selected. 

Regards,
Dragos

**Comment by sbatty** [comment]
I have the same issue. I want the menu to behave as the demo dashboard does. If the active page is a child node under another menu item i.e. "Regular Forms" under the parent menu item "Forms" the "Forms" menu item should not be collapsed. It is highlighted and marked as active but the parent menu item collapses and hides the active node.

**Comment by roshansingh21** [comment]
I have the same issue.
