### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by bbuehrle** [creativetimofficial/ct-material-dashboard-pro#105]
I purchased this template the other day (along with material kit pro) and only now got to look a little into the documentation.  I noticed that this is based from Bootstrap 3.  Is there a bootstrap 4 implementation in the works?

I'd like to be able to use both the material kit and the material dashboard together without having to include bootstrap 3 and 4 into my project.  Is this a quick fix where I can just change a couple of classes or would this require a complete rework of the code?

Sorry if this is a noob question.  I'm new at this and learning from the great school of Google. :)

**Comment by dragosct10** [comment]
Hi, @bbuehrle! Thank you for using our products. Yes, we work to migrate the product on Bootstrap 4, and I think in about 2 weeks you can download the product.

Regards, 
Dragos

**Comment by adwil13** [comment]
Hey @dragosct10 
How far are we from full Bootstrap 4 support? :)

**Comment by dragosct10** [comment]
Hi, @adwil13! We are almost ready with the product on BS4, and I think in 8-10 days maximum will be available, and also the support will be open. We were involved in other important things this period and that is the reason for the delay.

Regards,
Dragos

**Comment by adwil13** [comment]
@dragosct10 
Any updates ? :)

**Comment by ronindesign** [comment]
It's now been 2-3 weeks _after_ when release was expected, including answers on product page.

We have a few clients who can't go live until we've integrated the BS4 changes...

**Comment by dragosct10** [comment]
Hi! The product is available to download now. Regards, Dragos

**Comment by ronindesign** [comment]
@dragosct10 Thank you so much. Really appreciate it.

**Comment by ronindesign** [comment]
@dragosct10 I see old change log for **Material Dashboard PRO BS3** has extra change log entry missing from the new *2.0.0* version:

> **[1.2.1] 2017-11-17**
> 
> RTL Support
> - added new page with RTL Support
> 
> BugFixing
> - SweetAlert fixed on IE and browser console fixed error
> - Replaced es6-promise-auto.min.js library with core.js (CDN script)
> - Chartist.js fixed error from browser console
> - PerfectScrollbar fixed on IE
> 

However, the new **Material Dashboard PRO** (2.0.0) with BS4 shows a different change log entry:

> **[1.2.1] 2017-11-09**
> BugFixing
> - fixed parallax page scroll
> - fixed cards from ecommerce.html page

Are the other fixes included in the updated 2.0.0 as well, and just missing from the changelog?
There are some pretty important bug fixes in the first, so any info this is appreciated.

Thanks again for the hard work on this!

**Comment by ronindesign** [comment]
Also, if anyone is interested, here's a diff stat from ver `1.2.1` -> `2.0.0`.
_NB: Not including code diff since license is proprietary_

```git
 assets/css/material-dashboard.css      | 32602 ++++++++++++++++++++++++++++++++++++++++++----------------------------  assets/js/material-dashboard.js        |    94 +-
 examples/calendar.html                 |   911 +-
 examples/charts.html                   |  1094 +--
 examples/components/buttons.html       |  1824 ++--
 examples/components/grid.html          |  1322 +--
 examples/components/icons.html         |   920 +-
 examples/components/notifications.html |  1345 +--
 examples/components/panels.html        |  1427 ++--
 examples/components/sweet-alert.html   |  1022 +--
 examples/components/typography.html    |  1066 +--
 examples/dashboard.html                |  1581 ++--
 examples/forms/extended.html           |  1329 ++-
 examples/forms/regular.html            |  1449 ++--
 examples/forms/validation.html         |  1299 ++-
 examples/forms/wizard.html             |  1234 +--
 examples/maps/fullscreen.html          |   815 +-
 examples/maps/google.html              |   955 ++-
 examples/maps/vector.html              |   911 +-
 examples/pages/lock.html               |   306 +-
 examples/pages/login.html              |   383 +-
 examples/pages/pricing.html            |   398 +-
 examples/pages/register.html           |   459 +-
 examples/pages/rtl.html                |  1655 ++--
 examples/pages/timeline.html           |  1027 ++-
 examples/pages/user.html               |  1070 +--
 examples/tables/datatables.net.html    |  1988 ++---
 examples/tables/extended.html          |  1645 ++--
 examples/tables/regular.html           |  1491 ++--
 examples/widgets.html                  |  1672 ++--
```

Additions:
(Lot of new files, posting to Pastebin): https://pastebin.com/mnuR1r95

**Comment by dragosct10** [comment]
Hi, @ronindesign! We are sorry for this inconvenience. This problem with the changelog is just a text mistake from our side and we will fix this in the next update. 

Regards, 
Dragos

**Comment by ronindesign** [comment]
@dragosct10 I thought so, no problem at all. Thank you!
