### ISSUE TITLE
Only first card printed

### ISSUE THREAD

**Issue by gobusnuts** [creativetimofficial/ct-material-dashboard-pro#107]
Printing a page from the browser will only print the first card.

![image](https://user-images.githubusercontent.com/17452426/36453852-834f4c96-16fe-11e8-8c63-a73cffd3a5b9.png)

**Comment by dragosct10** [comment]
Hi, @gobusnuts! Thank you for using our product. You have an alternative to make this to work. You can install the `full screen page capture` extension of google chrome and this will capture all the page and then you can print it. 

Regards, Dragos

**Comment by gobusnuts** [comment]
Thanks, the user base does not make that an ideal solution. We will probably end up building a print friendly stylesheet that remotely resembles the screen output.

**Comment by dragosct10** [comment]
Hi, @gobusnuts! I noticed that if you have the latest version of the product, the print option will work because I tested and everything from the page is on the print capture. Do you have the latest version of the product? 

Regards,
Dragos

**Comment by gobusnuts** [comment]
Hi @dragosct10, 

I've tested with the latest version (1.2.1) with the same result. To confirm it's not something on our side, I tested with your preview site as well. http://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html?_ga=2.238711104.1979225067.1519592475-1558998284.1519164965
[cttp.pdf](https://github.com/creativetimofficial/material-dashboard-pro/files/1756760/cttp.pdf)

The attached PDF was printed from Firefox.
A more accurate description to the problem would be that only the first page gets printed. It looks like the page size matters. See this result after I set the page size to A3.
[cttp A3.pdf](https://github.com/creativetimofficial/material-dashboard-pro/files/1756764/cttp.A3.pdf)

Is there something in the CSS that cuts off content outside the rendered screen, similar to overflow?

**Comment by dragosct10** [comment]
Hi, @gobusnuts! I will show you a [video](https://www.dropbox.com/s/u2mq5lnwmmwlx37/md-pro-print.mov?dl=0) and you will see that the print preview is working. I tested on a Mac. The problem is very weird, please try to remove the property `overflow` from the .main-panel and .sidebar-wrapper. 

Regards,
Dragos
