### ISSUE TITLE
select with no animations

### ISSUE THREAD

**Issue by ruinunes** [creativetimofficial/ct-material-dashboard-pro#108]
- using `data-style="select-with-transition"` the select only shows the line animation, if setting the `multiple` option.
- when clicking on it, does not animate into view. It suddenly appears. In constrast, in the demo page if you constrain the height of the window, then when clicking the dropup animation kicks in.

**Comment by dragosct10** [comment]
Hi, @ruinunes! Thank you for using our product. Please, can you give us an image or video to see what happened there? 

Regards, 
Dragos
