### ISSUE TITLE
Why do not have this setting option

### ISSUE THREAD

**Issue by dongguowang** [creativetimofficial/ct-material-dashboard-pro#109]
<img width="1476" alt="aa1" src="https://user-images.githubusercontent.com/36839041/36668505-8438e5d6-1b2c-11e8-9823-cfd939fcc640.png">
<img width="1507" alt="aaa2" src="https://user-images.githubusercontent.com/36839041/36668556-a0f58b48-1b2c-11e8-9358-91ddc3f2e42b.png">

**Comment by dragosct10** [comment]
Hi, @dongguowang! Thank you for using our product. That fixed plugin it's not in your archive because that is used only for demo purpose. Do you need this plugin? 

Regards, 
Dragos

**Comment by FeddyCastro** [comment]
Hello, @ dragosct10 could you help me with that add-on please I would appreciate it very much

**Comment by dragosct10** [comment]
Hi! Please, give us your email address to send you there the files or you can write us on the support area and you will receive there the files. Regards, Dragos
