### ISSUE TITLE
Bootstrap Datetimepicker not working with latest release 4.17.47

### ISSUE THREAD

**Issue by JayChandler** [creativetimofficial/ct-material-dashboard-pro#110]
Your product is using version 4.17.37 of the bootstrap datetimepicker component. We are using version 4.17.47 and its not working anymore. The datetime picker is not showing up. Its only showing up using your version.

Any chance of upgrading it to 4.17.47 ? 

Thx

**Comment by JorgenSolli** [comment]
Just went through this myself.

If you want to use .47, override or replace your _plugin-datetime-picker.scss with this https://github.com/JorgenSolli/Logit/blob/master/resources/assets/sass/material-dashboard/plugins/_plugin-datetime-picker.scss

It's not perfect, but it works fine. Hoping the new release with bootstrap 4 will come with .47 :)

**Comment by JayChandler** [comment]
Yeah its working. The picker is showing up. But the toggle for the time picker is not working anymore.

**Comment by JayChandler** [comment]
i can't get this working

**Comment by dragosct10** [comment]
Hi! The latest version of the datetimepicker is for BS4. I hope we will launch the new Material Dashboard on BS4 in one week, so when we will launch the product the datetimepicker will also be updated. 

Regards, Dragos

**Comment by JayChandler** [comment]
Thats interesting because we run that version with plain vanilla Bootstrap 3 and it worked without any problems ...

**Comment by Stackout** [comment]
I need this for a client's backend portal, and it had to stop working. Nice...

**Comment by JorgenSolli** [comment]
Just revert back to .37 for now? I don't see the problem.
