### ISSUE TITLE
Incorrect docs

### ISSUE THREAD

**Issue by ruinunes** [creativetimofficial/ct-material-dashboard-pro#111]
![image](https://user-images.githubusercontent.com/2411102/36776918-ca436484-1c67-11e8-8306-bed9cd6597c8.png)

**Comment by dragosct10** [comment]
Hi, @ruinunes! Thank you for your observation. You have right the text it's not good, but the links are good. We will fix this in the next update. 

Regards,
Dragos

**Comment by ruinunes** [comment]
Also please help:
material-dashboard-pro-html-v1.2.1/documentation/tutorial-components.html
is now a broken link for the online documentation.

**Comment by dragosct10** [comment]
Hi! Please use this [link](http://demos.creative-tim.com/bs3/material-dashboard-pro/documentation/tutorial-components.html) and we also will make an update for it. 

Regards,
Dragos
