### ISSUE TITLE
Checkbox and radio button properties

### ISSUE THREAD

**Issue by ruinunes** [creativetimofficial/ct-material-dashboard-pro#112]
When clicking on the checkbox the circle simply fades.
When clicking the radio button, the circle grows and fades.

Would look better, if they were as the radio button.

Radio button positioning and size also feel odd, when having radio buttons and checkboxes aligned vertically in the same form.

**Comment by dragosct10** [comment]
Hi, @ruinunes! You say it will be better if the animation from the radio will be also on the checkbox input right? Regards, Dragos

**Comment by ruinunes** [comment]
Yes, I would say that.

**Comment by ruinunes** [comment]
Another issue: when loading a page with a checkbox, the ripple effect appears without necessity.
