### ISSUE TITLE
Font Awesomeicon for accordion

### ISSUE THREAD

**Issue by Extarys** [creativetimofficial/ct-material-dashboard-pro#113]
Replacing `<i class="material-icons">keyboard_arrow_down</i>` with `<i class="far fa-angle-down"></i>` using SVG library, the icon does not rotate nor is right-aligned.

How should I able this?

Thanks!!

**Comment by groovemen** [comment]
Hello @Extarys, thank you for using our template and sorry for this big delay, please send to us a link to your project to check the problem. It should work just fine. All the best, Stefan
