### ISSUE TITLE
Modal not working on iPhone

### ISSUE THREAD

**Issue by Python4569** [creativetimofficial/ct-material-dashboard-pro#116]
A simple modal opened with  $("#modal").modal(); or $("#modal").modal('show'); does not work on iPhone but yes in any other device. The modal remains with the black effect and can not be clicked on.

Only works deleting the black background with $("#modal").modal({backdrop: false}); and I do not want to delete it...

**Comment by dragosct10** [comment]
Hi, @Python4569! Thank you for using our product. Please tell us which version of the product do you have? Regards, Dragos
