### ISSUE TITLE
material-dashboard.js - Uncaught ReferenceError: demo is not defined

### ISSUE THREAD

**Issue by ronindesign** [creativetimofficial/ct-material-dashboard-pro#117]
Console error:
```
Uncaught ReferenceError: demo is not defined
    at material-dashboard.js?v=2.0.1:217
(anonymous) @ material-dashboard.js?v=2.0.1:217
```

Relevant code:
```javascript
// activate collapse right menu when the windows is resized
$(window).resize(function() {
    md.initSidebarsCheck();

    // reset the seq for charts drawing animations
    seq = seq2 = 0;

    setTimeout(function() {
        demo.initDashboardPageCharts();
    }, 500);
});
```

**Comment by ronindesign** [comment]
@JorgenSolli I don't want to use it, but since it's in the core `material-dashboard.js` file, it gets called.

**Comment by JorgenSolli** [comment]
Yeah you're right. It should be defined in the file you're referring to. But for now, it seems we're gonna have to just include the demo.js file :/

**Comment by ronindesign** [comment]
I'm simply reporting this bug so they can fix their core code.

I've already added an empty function to do nothing when called:
```javascript
demo = {
  initDashboardPageCharts: function() {}
}
```

**Comment by dragosct10** [comment]
Hi! Thank you for using our product and for observation of this bug. You are right the function that it's called must be in the same file. We will fix this in the next update. Regards, Dragos
