### ISSUE TITLE
Undefined mixin 'shadow-small-color'

### ISSUE THREAD

**Issue by lrjbrual** [creativetimofficial/ct-material-dashboard-pro#119]
Hi Team, 

I would like to seek your favorable assistance for Undefined mixin 'shadow-small-color'. here's the screenshot. I hope to hear you soon as possible. it happens when I migrating to new change log from Version 1.2.1  to Version 2.0.1

![image](https://user-images.githubusercontent.com/9385561/37933488-a7e1205e-314b-11e8-8961-f40309614ea1.png)

Hoping to hear you soon. 

Thanks

**Comment by dragosct10** [comment]
Hi, @lrjbrual! Did you put all scss from the new update to your rails project? Regards, Dragos

**Comment by lrjbrual** [comment]
@dragosct10 now I resolved the layouts. but I think there some miss alignment of importing files: 

Here's on what I have: 
![image](https://user-images.githubusercontent.com/9385561/38034598-ebb2f3ae-32a2-11e8-8c9d-258802bf31da.png)

What is the core our our bootstrap to use in 2.0.1? I think I have missing and overkill using all the files we have on the template. hope to hear you soon.

**Comment by dragosct10** [comment]
Hi! In the image that you attached it's obviously that you don't have the css imported. Please give us your link to see what happened there. Regards, Dragos
