### ISSUE TITLE
Conflict with select option in navigation pills

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#121]
Hi, since an update (I think it's boostrap 4), the selection fields have a conflict if they are in a navigations pills. When you click on a button, to change the tab, the arrows of the selection fields go back, as if you had just opened all the selection fields, and remain locked in this position.

![navpill](https://user-images.githubusercontent.com/27307704/38116308-7e055474-337d-11e8-966b-54dc97164413.gif)

**Comment by dragosct10** [comment]
Hi, @KonScyence! Thank you for using our product. Please, can you give us the link of your project to see what happened there? Regards, Dragos

**Comment by KonScyence** [comment]
Here is the link !
http://klam.shost.ca/test/

**Comment by dragosct10** [comment]
Hi, @KonScyence! Please first remove all the javascript errors from your console and then I think that the caret will work because it's from bootstrap and I think that errors prevent the caret to work. Regards, Dragos

**Comment by KonScyence** [comment]
Now there is no more error, but the problem is still there @dragosct10.

**Comment by KonScyence** [comment]
Hi, do you have a solution in CSS please, I have never used the SCSS ... :)

**Comment by killer3dfx** [comment]
Hello, this also happen when you place a Select on a collapsible Div. @dragosct10

**Comment by dragosct10** [comment]
Hi, @killer3dfx! Thank you for using our product and for your observation. Yes, it is possible to be the same issue there in the collapse because also the class `.show` appear. We will fix it in the next release. Regards, Dragos

**Comment by dragosct10** [comment]
Hi, @KonScyence! This fix that I gave you it's a css fix and you can use it how you want, also in `.css` file extension and also in `.scss` extension.
