### ISSUE TITLE
datetimepicker error in form 

### ISSUE THREAD

**Issue by sebastianro92** [creativetimofficial/ct-material-dashboard-pro#124]
![issue](https://user-images.githubusercontent.com/21010074/38569641-6ab9d038-3cb1-11e8-9669-f5582f69d7ab.gif)

**Comment by dragosct10** [comment]
Hi, @sebastianro92! Thank you for using our product. Please take the uploaded file and go in assets/js and replace there the file. Regards, Dragos 

[bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/1898289/bootstrap-material-design.js.zip)

**Comment by sebastianro92** [comment]
thanks bro !

**Comment by jeanrespen** [comment]
Hello, what was the issue? Can you release a minified version as well ? I was struggling with this bug for hours... Best, Jean

**Comment by dragosct10** [comment]
Hi, @jeanrespen! Thank you for using our product. The problem was in that js file from another library that we use with some lines of code that trigger all the classes with name `date-anyname`, so we modified this to not trigger anymore these classes. You can minify the js file [here](https://javascript-minifier.com/). Regards, Dragos

**Comment by shaileishrana** [comment]
Hi , I am facing the same issue above, in material-dashboard-pro-html-v2.0.1.
I am unable to download the fix that you have uploaded , the link does not seem to be working now. 
Can you please provide a working link to download.

**Comment by dragosct10** [comment]
Hi, @shaileishrana! Thank you for using our product. Of course, please see below the link attached. 

https://www.dropbox.com/s/2ee2z1t3fu0n1bz/bootstrap-material-design.js.zip?dl=0

Regards, 
Dragos
