### ISSUE TITLE
datalivesearch not working in select

### ISSUE THREAD

**Issue by killer3dfx** [creativetimofficial/ct-material-dashboard-pro#125]
when adding a datalivesearch property to selectpicker, I can see the seach input but no results when searching or content any content filtered.

`<select class="selectpicker" data-size="7" data-style="btn btn-primary btn-round" title="Tug" data-live-search="true">`

![datalivesearch](https://user-images.githubusercontent.com/38220484/38582793-8ad85bee-3cd6-11e8-81ed-388fc621eb8c.gif)
![datalivesearcherror](https://user-images.githubusercontent.com/38220484/38582920-f82b83a6-3cd6-11e8-8368-844ec9fcdbf9.gif)

**Comment by killer3dfx** [comment]
Ok, I solved it, I want to share my solution.

First there is some incompatibility between: arrive.min.js and bootstrap-selectpicker.js

then bootstrap-select plugin is not fully compatible with Bootstrap 4.

I added the following code to css and now works ok:

```
.bootstrap-select.show > .dropdown-menu > .dropdown-menu {
  display: block;
}
```

```
.bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden {
  display: none;
}
```

Hope this helps.

Looking forward to a solution for Issues #122, #123 and #124

**Comment by dragosct10** [comment]
Hi, @killer3dfx! Thank you for your solution. Yes, you are right the selectpicker plugin it's not fully compatible with BS4 because when we released the product BS4 version was not released, anyway now it's available and we will do an update for it. Regards, Dragos

**Comment by indradio** [comment]
sorry, i cannot understand

> 
> 
> Ok, I solved it, I want to share my solution.
> 
> First there is some incompatibility between: arrive.min.js and bootstrap-selectpicker.js
> 
> then bootstrap-select plugin is not fully compatible with Bootstrap 4.
> 
> I added the following code to css and now works ok:
> 
> ```
> .bootstrap-select.show > .dropdown-menu > .dropdown-menu {
>   display: block;
> }
> ```
> 
> ```
> .bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden {
>   display: none;
> }
> ```
> 
> Hope this helps.
> 
> Looking forward to a solution for Issues #122, #123 and #124

sorry, can you explain step by step? i need this feature too

**Comment by groovemen** [comment]
Hello @indradio, 

Thank you for using our products, this issue is solved in the last update so you need just to set your selectpicker like this and it will work just fine. 
```
<select class="selectpicker" data-size="7" data-style="btn btn-primary btn-round" title="Tug" data-live-search="true">
  <option disabled selected>Single Option</option>
  <option value="2">Foobar</option>
  <option value="3">Is great</option>
  <option value="4">Is bum</option>
  <option value="5">Is wow</option>
  <option value="6">boom</option>
</select>
```
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
