### ISSUE TITLE
Extended Select Options Required and Forms Validation ERROR

### ISSUE THREAD

**Issue by emanuelnogueiras** [creativetimofficial/ct-material-dashboard-pro#126]
in this page we can see the "choose city" example
https://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html

I need to use this control with form-control tag to validation forms...

If I do not put the "form-control" tag when try to submit the form, the submit is cancelled but no error or color or something is showing to know that this field are required...

When I put the "form-control" tag, in the "require" case, the control shows a primary color line on bottom but the style of the whole control is wrong..

It's doesn't work fine...

**Comment by dragosct10** [comment]
Hi, @emanuelnogueiras! Thank you for using our product. Please give us you link project to see what happens there. Regards, Dragos
