### ISSUE TITLE
events not working

### ISSUE THREAD

**Issue by ramsegev** [creativetimofficial/ct-material-dashboard-pro#128]
I'm using material dashboard pro HTML v2.0.1, it seems that events from bootstrap-material-design.js are not added to form-control, i have no errors in console and when i work with material dashboard pro html-v1.2.0 everything was working fine.
This pic is from my site
![image](https://user-images.githubusercontent.com/10572154/38776880-f45bd978-40a6-11e8-8eb9-074ffd8d59cb.png)
this is from the html example
![image](https://user-images.githubusercontent.com/10572154/38776915-9036fc74-40a7-11e8-85b2-3f811a03ace4.png)

please advise
Cheers
Ram

**Comment by groovemen** [comment]
Hello again @ramsegev, currently we are working on an update for this product, and by now it looks like the `form-control` class has all the events. Stay tuned for the update that is coming.
<img width="998" alt="screen shot 2018-05-29 at 15 32 14" src="https://user-images.githubusercontent.com/21063398/40658952-7e5fb29a-6355-11e8-8a5b-158e846e50ea.png">
 Best, Stefan
