### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/ct-material-dashboard-pro#130]
You have an issue here. 
![image](https://user-images.githubusercontent.com/16140960/38837395-d4210d00-419f-11e8-846b-5a492675e977.png)

but in your angular version of material dashboard its working well
![image](https://user-images.githubusercontent.com/16140960/38837415-ee40c798-419f-11e8-9d0f-8c2dd7840938.png)

This is by showing scrollbar on bootstrap version... how to solve this?

**Comment by dragosct10** [comment]
Hi, @israelias94! Thank you for using our product. Please tell me which version of the product do you have? Regards, Dragos

**Comment by israelias94** [comment]
Im using 2.0.1 versión of material dashboard pro html.

However. Those screenshoots were taking From your "Live Preview"

Thanks for  your response!

**Comment by dragosct10** [comment]
Hi! This is weird because I just test it in Windows and the scrollbar is activated and is working fine. Which browser do you use? Regards, Dragos

**Comment by israelias94** [comment]
I'm using Chrome on Linux

It's true, I tested it on Windows with the "Version 65.0.3325.181 (Official Build) (64-bit)" build of Chrome and it works, and on Linux I'm with the same version of Chrome and it fails.

Why?

Actually, my customers use Windows and this is closed for me, but why does it fail on Linux system? Do you have an answer?


Thanks.

**Comment by dragosct10** [comment]
Hi, @israelias94! I think it is a problem from our javascript file where we initialize the scrollbar plugin because we initialize only if windows is the operating system, so I think this is the problem here. Anyway, we will add this condition in the next update. Regards, Dragos
