### ISSUE TITLE
Purchased 'Material Design PRO' and downloads page doesn't work

### ISSUE THREAD

**Issue by Makiavelo** [creativetimofficial/ct-material-dashboard-pro#131]
Here is the error on the downloads page:

<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>
Error parsing the X-Amz-Credential parameter; the region 'eu-east-1' is wrong; expecting 'us-east-1'
</Message>
<Region>us-east-1</Region>
<RequestId>8D3A8DC8366690B0</RequestId>
<HostId>
bT0c2c6u3M35nqLZIQWWZbmGyyvf3K+ZgdtY1vmK/xJ+tIufYhjkcynJV8LDzgLeaMy65DZEVU8=
</HostId>
</Error>

**Comment by dragosct10** [comment]
Hi, @Makiavelo! Thank you for using our product. We are sorry for the inconvenience. Please, try to download again the product because we fixed it. Regards, Dragos
