### ISSUE TITLE
dropdown-header

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#133]
Hi, the bootstrap class dropdown-header is not really suited to the theme.

**Example**

In the slidebar:
![mode_menu](https://user-images.githubusercontent.com/27307704/39022611-5be565fe-4404-11e8-8ad1-a44f743ab878.PNG)

In the menu:
![icon mode](https://user-images.githubusercontent.com/27307704/39022619-65f68ece-4404-11e8-8884-3af33ee040a5.PNG)

Regards

**Comment by dragosct10** [comment]
Hi! You can add in scss the color white on the dropdown-header. We will fix this in the next update too. Regards, Dragos

**Comment by groovemen** [comment]
Hello @KonScyence, 
thank you for using our templates, you can set as in [Bootstrap's example](http://getbootstrap.com/docs/4.1/components/dropdowns/#headers) a dropdown header and it will work just fine. Check the photos attached below:

<img width="385" alt="screen shot 2018-05-29 at 14 45 29" src="https://user-images.githubusercontent.com/21063398/40657072-37e4de5e-634f-11e8-9f15-cf3c57eadbee.png">
<img width="525" alt="screen shot 2018-05-29 at 14 45 35" src="https://user-images.githubusercontent.com/21063398/40657073-38044c76-634f-11e8-9e72-7f43cba8ae02.png">

But in this example that you showed to us:

<img width="246" alt="screen shot 2018-05-29 at 14 47 52" src="https://user-images.githubusercontent.com/21063398/40657146-6cd7a8da-634f-11e8-9739-cfd9a7761df3.png">

- you are using a `dropdown-header` class inside of a `collapse`, which is not good. This class should be placed in a `dropdown-menu`.

Please let us know if it works after you make these changes.

All the best, 
Stefan
