### ISSUE TITLE
Material Wizard integration

### ISSUE THREAD

**Issue by TheTrueElektro** [creativetimofficial/ct-material-dashboard-pro#136]
Hi, i copied the forms/wizard.html page and integrated the js part (inside demo.js) into a personnal class. I added some 'var' in front of some var declaration because i got errors from console. here is my issue : 

When i load the page the tab indicator does not show well.

However if i resize my window, it directly set up correctly. any idea? 

<img width="958" alt="screen shot 2018-04-24 at 16 11 31" src="https://user-images.githubusercontent.com/11785727/39192952-b6a6b9aa-47da-11e8-8e7f-5b2d6113c93e.png">

<img width="933" alt="screen shot 2018-04-24 at 16 11 43" src="https://user-images.githubusercontent.com/11785727/39192959-b8dd1c32-47da-11e8-8838-8d139b3d211e.png">

Thanks for reading

**Comment by TheTrueElektro** [comment]
By adding $(window).trigger('resize'); at the end of the js i can get the hover correctly, however it will get dirty again si i switch tab.. i think there is a problem with my vars initialisation somewhere

**Comment by dragosct10** [comment]
Hi, @TheTrueElektro! Thank you for using our product. Do you fix the problem, or this still persist because on our part the initialization it's ok the tabs have the correct width? Regards, Dragos

**Comment by TheTrueElektro** [comment]
Hi, Well the problem is that pink hover is still at the good width when i switch tab :/ it is working in the example files and i just copy pasted js for testing purpose :/ i'm kind of lost. here is my js : 

`class Wizard {

	initClientsCreateWizard()
	{
		var $validator, $total, $li_width, index_temp, vertical_level, mobile_device;

		function simReload()
		{
			$(window).trigger('resize');
		}

		// Code for the Validator
		$validator = $('.wizard-card form').validate({
			rules: {
				organisation_name: {
					required: true,
					minlength: 4
				},
				organisation_short_name: {
					required: false,
					minlength: 4
				},
				email: {
					required: false,
					minlength: 3,
				}
			},

			errorPlacement: function(error, element) {
				$(element).parent('div').addClass('has-error');
			}
		});

		// Wizard Initialization
		$('.wizard-card').bootstrapWizard({
			'tabClass': 'nav nav-pills',
			'nextSelector': '.btn-next',
			'previousSelector': '.btn-previous',

			onNext: function(tab, navigation, index) {
				$valid = $('.wizard-card form').valid();
				if (!$valid) {
					$validator.focusInvalid();
					return false;
				}
			},

			onInit: function(tab, navigation, index) {
				//check number of tabs and fill the entire row
				$total = navigation.find('li').length;
				$wizard = navigation.closest('.wizard-card');

				$first_li = navigation.find('li:first-child a').html();
				$moving_div = $('<div class="moving-tab">' + $first_li + '</div>');
				$('.wizard-card .wizard-navigation').append($moving_div);

				refreshAnimation($wizard, index);

				$('.moving-tab').css('transition', 'transform 0s');
			},

			onTabClick: function(tab, navigation, index) {
				$valid = $('.wizard-card form').valid();

				if (!$valid) {
					return false;
				} else {
					refreshAnimation($wizard, index);
					return true;
				}
			},

			onTabShow: function(tab, navigation, index) {
				$total = navigation.find('li').length;
				$current = index + 1;

				$wizard = navigation.closest('.wizard-card');

				// If it's the last tab then hide the last button and show the finish instead
				if ($current >= $total) {
					$($wizard).find('.btn-next').hide();
					$($wizard).find('.btn-finish').show();
				} else {
					$($wizard).find('.btn-next').show();
					$($wizard).find('.btn-finish').hide();
				}

				button_text = navigation.find('li:nth-child(' + $current + ') a').html();

				setTimeout(function() {
					$('.moving-tab').text(button_text);
				}, 150);

				checkbox = $('.footer-checkbox');

				if (!index == 0) {
					$(checkbox).css({
						'opacity': '0',
						'visibility': 'hidden',
						'position': 'absolute'
					});
				} else {
					$(checkbox).css({
						'opacity': '1',
						'visibility': 'visible'
					});
				}

				refreshAnimation($wizard, index);
			}
		});


		// Prepare the preview for profile picture
		$("#wizard-picture").change(function() {
			readURL(this);
		});

		$('[data-toggle="wizard-radio"]').click(function() {
			wizard = $(this).closest('.wizard-card');
			wizard.find('[data-toggle="wizard-radio"]').removeClass('active');
			$(this).addClass('active');
			$(wizard).find('[type="radio"]').removeAttr('checked');
			$(this).find('[type="radio"]').attr('checked', 'true');
		});

		$('[data-toggle="wizard-checkbox"]').click(function() {
			if ($(this).hasClass('active')) {
				$(this).removeClass('active');
				$(this).find('[type="checkbox"]').removeAttr('checked');
			} else {
				$(this).addClass('active');
				$(this).find('[type="checkbox"]').attr('checked', 'true');
			}
		});

		$('.set-full-height').css('height', 'auto');

		//Function to show image before upload

		function readURL(input) {
			if (input.files && input.files[0]) {
				reader = new FileReader();

				reader.onload = function(e) {
					$('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
				}
				reader.readAsDataURL(input.files[0]);
			}
		}

		$(window).resize(function() {
			$('.wizard-card').each(function() {
				$wizard = $(this);

				index = $wizard.bootstrapWizard('currentIndex');
				refreshAnimation($wizard, index);

				$('.moving-tab').css({
					'transition': 'transform 0s'
				});
			});
		});

		function refreshAnimation($wizard, index) {
			$total = $wizard.find('.nav li').length;
			$li_width = 100 / $total;

			total_steps = $wizard.find('.nav li').length;
			move_distance = $wizard.width() / total_steps;
			index_temp = index;
			vertical_level = 0;

			mobile_device = $(document).width() < 600 && $total > 3;

			if (mobile_device) {
				move_distance = $wizard.width() / 2;
				index_temp = index % 2;
				$li_width = 50;
			}

			$wizard.find('.nav li').css('width', $li_width + '%');

			step_width = move_distance;
			move_distance = move_distance * index_temp;

			$current = index + 1;

			if ($current == 1 || (mobile_device == true && (index % 2 == 0))) {
				move_distance -= 8;
			} else if ($current == total_steps || (mobile_device == true && (index % 2 == 1))) {
				move_distance += 8;
			}

			if (mobile_device) {
				vertical_level = parseInt(index / 2);
				vertical_level = vertical_level * 38;
			}

			$wizard.find('.moving-tab').css('width', step_width);
			$('.moving-tab').css({
				'transform': 'translate3d(' + move_distance + 'px, ' + vertical_level + 'px, 0)',
				'transition': 'all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1)'
			});
		}
		simReload();
	}

}
`

**Comment by dragosct10** [comment]
Hi, @TheTrueElektro! You tried to take the javascript code for the wizard like you found it in the project that you downloaded from our site because that code is good like you saw on our site is working fine the wizard? Regards, Dragos

**Comment by TheTrueElektro** [comment]
Hey, yes i downloaded the all code from the account page on your website :P

**Comment by dragosct10** [comment]
Hi, @TheTrueElektro! Please, can you give us access to your project to see what is happening there because it's hard to figure out like this? Regards, Dragos
