### ISSUE TITLE
Conflict with datetimepicker avec form element

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#141]
Hi, like you can see on [http://klam.shost.ca/test/](http://klam.shost.ca/test/), if I put the datetimepicker in a form element, the datetimepicker is no more working properly (You can not press on button, or change month).

![datetimepicker](https://user-images.githubusercontent.com/27307704/39731205-248879fa-5234-11e8-8a6b-2709b7f83500.gif)

Regards

**Comment by dragosct10** [comment]
Hi, @KonScyence! Please take the uploaded javascript file and put in assets/js. After that this will work for you. Regards, Dragos 

https://www.dropbox.com/s/2ee2z1t3fu0n1bz/bootstrap-material-design.js.zip?dl=0
