### ISSUE TITLE
datetimepicker not working

### ISSUE THREAD

**Issue by ebubekirguler** [creativetimofficial/ct-material-dashboard-pro#143]
hi,
I use [this](http://demos.creative-tim.com/bs3/material-dashboard-pro/documentation/tutorial-components.html#datetimepicker-row) example. But result:
![datetimepickererror](https://user-images.githubusercontent.com/4025593/39830243-76347f2e-53c9-11e8-9099-e2e91a034f73.gif). I can not select ant date. And there are no errors in the console.

**Comment by dragosct10** [comment]
Hi, @ebubekirguler! Thank you for using our product. Did you use the BS3 version of the product? Regards, Dragos

**Comment by ebubekirguler** [comment]
Hi @dragosct10,
Thanks for your quick reply. Yes. I use Material Dashboard PRO - V1.2.1

**Comment by dragosct10** [comment]
Hi, @ebubekirguler! Please, can you give us your link to the project to see what is happening there? Regards, Dragos

**Comment by dragosct10** [comment]
Hi! Yes you are right in the docs the datetimepicker it's not working because we have some errors there, but in the archive that you downloaded from our site the datetimepicker it's working fine. I think you also have some errors in your console so this is the reason that I ask you for the link to the project to see that. Regards, Dragos

**Comment by avijayaattri** [comment]
hi, I use the datetimepicker in my form but it only showing the input value and calender widget is not appear and not time.
![github](https://user-images.githubusercontent.com/40054018/41143914-b3017ac2-6b18-11e8-9cec-5cbb5fe54c0b.PNG)

**Comment by groovemen** [comment]
Hello @avijayaattri, probably it's because you initialized a **datepicker** and you expect to see the **datetimepicker**.  Please make sure that you didn't miss anything. Best, Stefan

**Comment by avijayaattri** [comment]
Thanks @groovemen for reply , but i din't initialize datepicker i used the datetimepicker with this code 

<div class="form-group">
    <label class="label-control">Datetime Picker</label>
    <input type="text" class="form-control datetimepicker" value="10/05/2016"/>
</div>
CopyCopy

$('.datetimepicker').datetimepicker({
    icons: {
        time: "fa fa-clock-o",
        date: "fa fa-calendar",
        up: "fa fa-chevron-up",
        down: "fa fa-chevron-down",
        previous: 'fa fa-chevron-left',
        next: 'fa fa-chevron-right',
        today: 'fa fa-screenshot',
        clear: 'fa fa-trash',
        close: 'fa fa-remove'
    }
});
but it is not showing time in my database the values of date are storing but not time.
