### ISSUE TITLE
How to move sidebar from Right side to Left Side while on Mobile device?

### ISSUE THREAD

**Issue by roshansingh21** [creativetimofficial/ct-material-dashboard-pro#145]

**Comment by dragosct10** [comment]
Hi, @roshansingh21! Thank you for using our product. Please add on the body tag the class `.menu-on-left`. 

Regards,
Dragos

**Comment by roshansingh21** [comment]
Thank you for the prompt response and May I know how to get that icon which
opens and closes sidebar to left hand side.

**Comment by dragosct10** [comment]
Hi! Do you want to know the name of that icon? Regards, Dragos

**Comment by groovemen** [comment]
Hello @roshansingh21, here is the icon that you asking for <i class="material-icons">more_vert</i>
