### ISSUE TITLE
Modal don't close correctly when route change 

### ISSUE THREAD

**Issue by lnrd256** [creativetimofficial/ct-material-dashboard-pro#146]
When the route change clicking in the back button from the explorer, the shadow modal still open and I can't make click in any site. 
Also this happen with the mini sidebar, when I click in any link with the modal oppened, this one don't close correctly.
![image](https://user-images.githubusercontent.com/6243628/40087718-e116f07c-5871-11e8-810f-8897e8b46032.png)

**Comment by dragosct10** [comment]
Hi, @lnrd256! Thank you for using our product. Please use the correct repo for you issue [Material Dashboard PRO Angular](https://github.com/creativetimofficial/material-dashboard-pro-angular). Regards, Dragos
