### ISSUE TITLE
Multilevel Menu

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/ct-material-dashboard-pro#147]
Any sample on multilevel menu for this template?

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! Unfortunately, we don't have any sample with a multilevel menu dropdown, but we have in our plan to introduce in the next update this samples. Regards, Dragos

**Comment by angelcalvasp** [comment]
Awesome

**Comment by roshansingh21** [comment]
Any one who can provide an example for this.

**Comment by angelcalvasp** [comment]
Next version will come with one

**Comment by groovemen** [comment]
Hello guys, please check the latest version of the product **V2.0.2**. You'll find the multilevel dropdown example there.
Best, 
Stefan
