### ISSUE TITLE
Chaning color of card-header

### ISSUE THREAD

**Issue by PHPadawan** [creativetimofficial/ct-material-dashboard-pro#148]
Hi, 
I noticed that color changes in _brand.scss do not take effect in the card header.
The colors ,such as primary ("card-header-primary"), are hard-coded for card header in _cards.scss(lines 164-211).

**Comment by groovemen** [comment]
Hello @PHPadawan, thank you for using our templates, all you have to do is to change the **[filter-color="yourFavouriteColor"]** attribute, you have an example in `scss/pro/sections/_headers.scss` file (from line 5).
Hope this information helps you!

All the best, 
Stefan

**Comment by jgbranco** [comment]
I tried this but no changes happened.

**Comment by groovemen** [comment]
Hello @jgbranco, thank you for using our templates, all you have to do is to change the **[card-header-color="yourFavouriteColor"]** attribute, and set any color that you want to; after that, you have to recompile the sass files. 

All the best, 
Stefan

**Comment by jgbranco** [comment]
Thanks!, it worked!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>


*João Gabriel D. F. Branco*
*Empreendedor Digital*
http://joaobranco.com
joaobranco@joaobranco.com
Telefone: 44 99639872
Skype: jgbranco / Twitter: @jgdfb
