### ISSUE TITLE
Can't change the purple default color to the color of my logo

### ISSUE THREAD

**Issue by jgbranco** [creativetimofficial/ct-material-dashboard-pro#149]
I am not an expert on CSS and Bootstrap but I get around pretty well... Unfortunatly this time I can't find a way to change the default color witch is purple to a green color from my logo, I installed node but don't know how to use it and when I change the _brand.scss file nothing happens.

**Comment by jgbranco** [comment]
On the documentation I found this:

1) Download the project’s zip
2) Make sure you have node.js (https://nodejs.org/en/) installed
3) Type npm install in terminal/console in the source folder where package.json is located
4) You will find all the branding colors inside assets/scss/core/variables/_brand.scss. You can change them with a HEX value or with other predefined variables from assets/scss/core/variables/_colors.scss
5) Run in terminal gulp compile-scss for a single compilation or gulp watch for continous compilation of the changes that you make in *.scss files. This command should be run in the same folder where gulpfile.js and package.json are located
6) Run in terminal gulp open-app for opening the Presentation Page (default) of the product. You can set in gulpfile.js from your downloaded archive any page you want to open in browser, at line 30: gulp.src('./examples/dashboard.html')

But I'm not an expert and wasn't able to get the third step done, and none after that.

**Comment by groovemen** [comment]
Hello @jgbranco, thank you for using our products! if you follow the steps from above correctly you'll change the primary color as you want. So, let's try again:
- access your terminal and execute **npm install**
- next, run **gulp open-app** (your project will be opened in a new browser window)
- go to: assets/scss/core/variables/_brand.scss and change the primary color to your green color from the logo
<img width="487" alt="screen shot 2018-05-29 at 13 41 58" src="https://user-images.githubusercontent.com/21063398/40654146-15b4d5fe-6346-11e8-9df4-5746188e547e.png">
- go to the dashboard page and refresh it again. It should work just fine!

<img width="1105" alt="screen shot 2018-05-29 at 13 39 20" src="https://user-images.githubusercontent.com/21063398/40654325-a3521af2-6346-11e8-9796-1e8030bc8acb.png">

*please let us know if it worked


All the best, 
Stefan

**Comment by willdev21** [comment]
Hi what about changing the color in material dashboard react pro
There is no a _brand.scss file

**Comment by willdev21** [comment]
I have changed in variables.scss then run "yarn run compile-sass" but the primary color could not be changed any help please

**Comment by groovemen** [comment]
Hello @willdev21 
Thank you for using our products, please open the issue on the right product repository: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues 
Best, 
Stefan
