### ISSUE TITLE
How to put image on checkbox/radio ?

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#150]
Hi, I'm trying to add HTML after the radio button, but I'm not able. Here is a example: http://klam.shost.ca/test/

Regards

**Comment by dragosct10** [comment]
Hi! We can't understand what you want to do. Please, show us an example of what you want to achieve. Regards, Dragos

**Comment by KonScyence** [comment]
Hi, as you see in the link send before, I want to put images, text... after the button.

Regards
