### ISSUE TITLE
White bar with the menu on mobile

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-material-dashboard-pro#151]
Hi, like you can see on http://klam.shost.ca/test/. When you go on mobile size (menu on right), and you open the menu, their is a white line at the bottom of the page that appeared.

![menuwhite](https://user-images.githubusercontent.com/27307704/40258762-a4ae512e-5ac0-11e8-9ed4-25fe39975d42.gif)

Regards

**Comment by dragosct10** [comment]
Hi, @KonScyence! I've tried to reproduce the issue on our live preview demo and it's working fine and also it's working fine on your link. Regards, Dragos
