### ISSUE TITLE
Sidebar Issue not opening

### ISSUE THREAD

**Issue by rodriguezwalter** [creativetimofficial/ct-material-dashboard-pro#152]
Hi, i got the pro version of the theme, but when i try to make the login page, the sidebar doesnt open when you resize the window and click on the icon. Everything else is workin so im really clueless here. ive use the templates for the navbars and it doesnt work either. 

Please help me out! thanks!!!

**Comment by dragosct10** [comment]
Hi, @rodriguezwalter! Thank you for using our product. Please, can you tell us how to reproduce the issue because in our part the sidebar is working fine? Regards, Dragos
