### ISSUE TITLE
Input Mask (Currency)

### ISSUE THREAD

**Issue by jhonvp** [creativetimofficial/ct-material-dashboard-pro#154]
Hello

I'm trying to implement a currency input mask but I'm having trouble.

Anyone could implment something similar?

Regards

**Comment by KonScyence** [comment]
Hi @jhonvp! I recommend you to use jQuery Mask Plugin from [igorescobar](https://github.com/igorescobar/jQuery-Mask-Plugin). It's an easy plugin to install, to use and with all the features you probably need.

To install it, simply drag one of the files from the directory `dist` into your `assets/js/plugins` directory (Or corresponding). After add it, into the file where you want to have it, at the bottom of it with other JS files. And here he is installed! Now you just have to read the very [complete documentation on the website](http://igorescobar.github.io/jQuery-Mask-Plugin/docs.html).

Regards!

**Comment by jhonvp** [comment]
Hello, I tried that but It does no have the mask I need, however, I solved the problem with http://autonumeric.org/.
