### ISSUE TITLE
datetime picker is not working 

### ISSUE THREAD

**Issue by avijayaattri** [creativetimofficial/ct-material-dashboard-pro#156]
hi, i use the datetimepicker in my form but it is not working it only showing the value of input , calendar widget is not appearing and also time is not there
![github](https://user-images.githubusercontent.com/40054018/41144208-bf5ccb2c-6b19-11e8-910d-fd7e0ab62f75.PNG)

**Comment by groovemen** [comment]
Hello @avijayaattri, thank you for using our products, please send us more details about this issue or share a link to your product. Did you initialize the datepicker in your page?

Best, Stefan

**Comment by groovemen** [comment]
This issue is fixed in the latest version of the product (V2.0.2).
Best, 
Stefan
