### ISSUE TITLE
Datetimepicker blinks when using it inside of a form tag

### ISSUE THREAD

**Issue by pueblodigital** [creativetimofficial/ct-material-dashboard-pro#159]
When you try to put a form tag and then if you have a datetime inside that form it makes the datetimepicker to start blinking when you put the mouse over a date.

Please help.

![calendario](https://user-images.githubusercontent.com/40075286/41183218-5c639162-6b2e-11e8-9b0d-2b04ba858a68.jpg)

**Comment by dragosct10** [comment]
Hi, @pueblodigital! Thank you for using our product. Please take the uploaded library and go to the project and replace the library. After that will work fine and also this will come in the next update which will be these days. Regards, Dragos 

https://www.dropbox.com/s/2ee2z1t3fu0n1bz/bootstrap-material-design.js.zip?dl=0

**Comment by pueblodigital** [comment]
Thanks @dragosct10 !!!!

**Comment by lashisu** [comment]
This issue is still there. No fix yet.
