### ISSUE TITLE
Edge and Firefox issue on Pricing Page

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/ct-material-dashboard-pro#160]
Hello there Creative Tim Team the same issue that happens in #123 seems to happen on the pricing page
v2.0.1

**Comment by groovemen** [comment]
Hello @angelcalvasp, thank you for using our products, we know about that issue. We are currently working on a update for this product where all this issues will be fixed. We'll let you know about the releasing date. Best, Stefan

**Comment by angelcalvasp** [comment]
Kewl
