### ISSUE TITLE
SweetAlert2 update version.

### ISSUE THREAD

**Issue by adwil13** [creativetimofficial/ct-material-dashboard-pro#161]
Current version included in MD Pro is... 5.3.5 and it's 2 years old. Current version is 7.22.2, maybe it's time for an update? :)

**Comment by angelcalvasp** [comment]
I updated to the latest version and it looks weird, does this happen to you too?

**Comment by adwil13** [comment]
Yep, you have to remove sweetalert2 scss files included by Material Dashboard. SweetAlert2 JS already contains all styling required.

**Comment by groovemen** [comment]
Hello, thank you for using our products, please update the JS and SCSS files of the Sweetalert plugin with the ones attached below:

[sweetalert.zip](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/2127151/sweetalert.zip)

Then, compile again your project to see the changes.
All the best, 
Stefan
