### ISSUE TITLE
Bug on datetimepicker when i try to select a date

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/ct-material-dashboard-pro#162]
It occurs when I select a date for second time

![creativesuite](https://user-images.githubusercontent.com/16140960/41363225-67b11356-6f01-11e8-9274-d125f5cbca62.gif)

Do you have an idea why it occurs?

**Comment by groovemen** [comment]
Hello @israelias94, thank you for using our products, this issue is fixed in the latest version(V2.0.2). Please check this [link: ](https://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html).

All the best, 
Stefan
