### ISSUE TITLE
Uncaught Error: element: <input name="id"> requires class: form-control

### ISSUE THREAD

**Issue by filoteanuadrian** [creativetimofficial/ct-material-dashboard-pro#164]
Open chrome console and start to use the wizzard - you will get:

https://demos.creative-tim.com/material-dashboard-pro/examples/forms/wizard.html

![image](https://user-images.githubusercontent.com/12797990/41463863-ac353336-70a0-11e8-8e2c-e26be0868321.png)

**Comment by groovemen** [comment]
Hello @filoteanuadrian, thank you for using our products, we fixed this issue in the latest update of the product (V2.0.2). 

Best, Stefan
