### ISSUE TITLE
Feature Request: Hamburguer Button inside Hamburguer menu

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/ct-material-dashboard-pro#165]
Is there any way to place the hamburguer menu button  inside de menu button to the right of the text without dying? Any chance this could be added? if not any tips on getting started?

**Comment by groovemen** [comment]
Hello again @angelcalvasp, please provide more details because it's hard to understand what you mean. 
Best, Stefan

**Comment by angelcalvasp** [comment]
Sorry 

![image](https://user-images.githubusercontent.com/7502746/42117269-470370fa-7bc1-11e8-9f19-090b8a52b261.png)
