### ISSUE TITLE
CSS for selectpicker

### ISSUE THREAD

**Issue by Jacox98** [creativetimofficial/ct-material-dashboard-pro#166]
Isn't there possibility to customize the selectpicker?
![image](https://user-images.githubusercontent.com/35966887/41646786-f9540dae-7474-11e8-8dea-88fa02d9e0c8.png)
Thanks Tim

**Comment by groovemen** [comment]
Hello @Jacox98, thank you for using our products, if you want to change the design of the selectpicker, you have to set a `data-style` attribute for the `<seclect>` tag. 
For example, if you want a purple, round button you have to set like this:
```
<select class="selectpicker" data-style="btn btn-primary btn-round" title="Your Select">
  <option>Example</option>
  ....
</select>
```

All the best, 
Stefan
