### ISSUE TITLE
SelectPicker port not scrollable with scrollwheel or 2 finger scroll

### ISSUE THREAD

**Issue by thedumbtechguy** [creativetimofficial/ct-material-dashboard-pro#168]
Problem can be seen here.

https://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html
Under "Customisable Select" > Choose city.

I checked and selectpicker works fine. Problem stems apparently from your modifications.

**Comment by thedumbtechguy** [comment]
As this issue has been closed with no comment, I am not certain if the issue has been resolved or is still pending.
I would appreciate some feedback.

**Comment by groovemen** [comment]
Hello @thedumbtechguy,

Thank you for using our products, we just updated last week this product and I checked the problem that you have mentioned above and everything works just fine. I will ask you to share with us a link to your project to check for a solution if it still there.

All the best and sorry for the inconvenience,
Stefan

**Comment by thedumbtechguy** [comment]
Thank you.

I'll update and redeploy.
