### ISSUE TITLE
Calendar Issue when try to add an activity in mobile view

### ISSUE THREAD

**Issue by jorge-valvert** [creativetimofficial/ct-material-dashboard-pro#172]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ ]x I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
In calendar (Calendar.io), using mobile view, when I click oven

# Current Behavior
In mobile view, when  I click an specific day on Calendar, nothing happens.  
![screen shot 2018-07-01 at 14 52 59](https://user-images.githubusercontent.com/39167918/42138692-bdec9b1e-7d3e-11e8-8d3d-617e1ae0ab44.png)

# Failure Information (for bugs)

Nothing happens at mobilie view.  Only the calendar is shown but I´m not able to add any activity.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Develper tools (chrome)
2. Set mobile view
3. Open calendar (from  creative-tim angular dashboard pro demo is ok)
4. Try to add an activity

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Chrome browser and Iphoe
* Operating System: mac osx Sierra - Ios 12
* Browser and Version: Chrome 67.0.3396.99

**Comment by groovemen** [comment]
Hello @jorge-valvert, 

thank you for using our products, all you have to do to make the calendar work on mobile/tab view is to longpress on the day you want to select. The event for mobile you can find right [here](https://github.com/vaidik/jquery-longpress#longpress-a-jquery-plugin). Also, you can read [the full documentation of this plugin](https://fullcalendar.io/docs) to see that they configured like this, it's not from our JS files.

All the best, 
Stefan
