### ISSUE TITLE
bootstrapMaterialDesign.js incompatible with ckeditor4

### ISSUE THREAD

**Issue by Jacox98** [creativetimofficial/ct-material-dashboard-pro#173]
![image](https://user-images.githubusercontent.com/35966887/42152441-661ae542-7de0-11e8-9612-81243c6d3e0f.png)
How can i resolve it?Thanks a lot

**Comment by KonScyence** [comment]
Hi @Jacox98! Here is the file corrected: [https://www.dropbox.com/s/2ee2z1t3fu0n1bz/bootstrap-material-design.js.zip?dl=0](https://www.dropbox.com/s/2ee2z1t3fu0n1bz/bootstrap-material-design.js.zip?dl=0).

Courtesy of @dragosct10 ;)

Regards!

**Comment by Jacox98** [comment]
Now it is working!!! Thank u <3
