### ISSUE TITLE
Clicking on Account Person Icon does not show expected menu

### ISSUE THREAD

**Issue by rscorer** [creativetimofficial/ct-material-dashboard-pro#179]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When clicking on the top right "person" icon I expect a dropdown showing Account choices

<img width="204" alt="screenshot 2018-08-18 at 09 06 47" src="https://user-images.githubusercontent.com/1592698/44297250-3cad1300-a2c6-11e8-8c7b-c0d359dfa674.png">

# Current Behavior

Nothing happens when I click

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go to [Material Dashboard Pro Demo](https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html)
2. Click on Person icon in top right
3. Url changes to https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html#pablo but nothing happens

## Context

Fails on my internal project, but also on the demo page.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @rscorer,

Thank you for using our products, we will make an update this weekend and we will integrate a dropdown for that icon having profile items options. We appreciate your suggestion! 

Best, 
Stefan
