### ISSUE TITLE
Mini Sidebar NOT working Material dashboard pro html

### ISSUE THREAD

**Issue by Sachin124** [creativetimofficial/ct-material-dashboard-pro#180]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
![dashboardworks](https://user-images.githubusercontent.com/26019527/44298423-80247300-a300-11e8-8325-850c4a0263b1.png)

Please describe the behavior you are expecting

# Current Behavior
![dashboard](https://user-images.githubusercontent.com/26019527/44298382-bad9db80-a2ff-11e8-8146-ad8827683196.png)

What is the current behavior?
When I click the Dashboard button the sidebar is not going to the mini sidebar. It's sometime works some time not.

* Device: Desktop
* Operating System: Linux Mint
* Browser and Version: Chrome latest
# Failure Information (for bugs)
Hello I use this dashboard panel for my Angular project . I am not purchasing Angular theme because I purchased for My normal HTML project and now i am converting my project to Angular . now all working fine, but mini sidebar is not working sometimes or sometime works when i hit button for refresh 5 or more times then comes , i don't know why this problem is come, please note I Update also my jquery , and also added the Jquery CDN links but same problem.

**Comment by groovemen** [comment]
Hello @Sachin124,

Thank you for using our products, can you provide us a link to your project to check for the problem ?!

Best, 
Stefan
