### ISSUE TITLE
text-right overlaps sort icon in datatable 

### ISSUE THREAD

**Issue by kristoferdoman** [creativetimofficial/ct-material-dashboard-pro#182]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting:
Text right overlaps sort icon in datatable. 

# Current Behavior

What is the current behavior?

![screen shot 2018-08-20 at 11 26 49 am](https://user-images.githubusercontent.com/7988949/44353340-440e2100-a46c-11e8-8c6f-06ecd56634e4.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Load the page and observe. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iMac
* Operating System: macOS
* Browser and Version: Safari - Latest

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @kristoferdoman, 

Thank you for using our products and for letting us know about this issue, I will ask you to make the following change to fix this until the next update:
- change the <th> class from **text-right** to **text-center**
and should look like this:
<img width="234" alt="screen shot 2018-09-10 at 16 07 08" src="https://user-images.githubusercontent.com/21063398/45299605-c3938b00-b514-11e8-94e0-dd5709e8e423.png">

Hope that information helps you. Please let us know if we can help you with anything else.
Best, 
Stefan
