### ISSUE TITLE
Hello, I have a problem with data tables, I want to use ngx data table but when I use this the CSS classes is not applying on it. 

### ISSUE THREAD

**Issue by Sachin124** [creativetimofficial/ct-material-dashboard-pro#184]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed
- [ Yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
![expected](https://user-images.githubusercontent.com/26019527/44615354-1f43f000-a856-11e8-8d35-adb0442290a4.png)

Please describe the behavior you are expecting

# Current Behavior
![actual](https://user-images.githubusercontent.com/26019527/44615338-b6f50e80-a855-11e8-9631-522708fea2ba.png)

What is the current behavior?
# Failure Information (for bugs)
I am using the one of the best data table NGX because of no jquery or many reasons, but when i use this bootstrap table CSS classes is not working on this.
following is my code:

```
<div class="card-body">
       <ngx-datatable class="table table-striped table-no-bordered table-hover"
                        [rows]="rows"
                        [columns]="columns">
       </ngx-datatable>
 </div>
```

**Comment by groovemen** [comment]
Hello @Sachin124, 

Thank you for using our products, you have reported this issue on a different repository, please open this issue on the following [repo](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues). 

Best, 
Stefan
