### ISSUE TITLE
Issue with change event inside a form

### ISSUE THREAD

**Issue by lashisu** [creativetimofficial/ct-material-dashboard-pro#185]
# Prerequisites
Add below code to see the unexpected behavior
<code>
    $(document).on('change', '.form-control', function(){
      console.log(1);
    });
</code>

# Expected Behavior
With below code Expected Behavior is to get the console every time on value change (change event)
<code>
    $(document).on('change', '.form-control', function(){
      console.log(1);
    });
</code>

# Current Behavior
But getting the console log infinite times on focus of the element even without the value change. This is happening with every element(like textbox, textarea, radio, checkbox and every element) inside a form which is bind with "<b>change</b>" event.
<code>
    $(document).on('change', '.form-control', function(){
      console.log(1);
    });
</code>

# Failure Information (for bugs)
On adding "<b>change</b>" change event with form element inside a form causing issue. Event triggered infinite times just focusing on the element. Its is working fine without the form tag.

## Steps to Reproduce
1. Open <b>https://demos.creative-tim.com/material-dashboard/docs/2.0/components/forms.html</b>
2. Open browser console and run below code
<code>
    $(document).on('change', '.form-control', function(){
      console.log(1);
    });
</code>
3. Now focus on first input control. Actually in documentation first two sections( "Overview" & "Form controls") are inside a form. So check within these blocks, you will get the raised issue.

**Comment by groovemen** [comment]
Hello @lashisu,

Thank you for using our products, we know about this issue but it's from the Bootstrap Material Design framework, you can reproduce the same behaviour on the following [link](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/forms/) and you will see the same issue. 

You can solve this issue by setting:
`$('body').bootstrapMaterialDesign({autofill:false});`

All the best, 
Stefan
