### ISSUE TITLE
Only load scripts if they are needed

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-dashboard-pro#186]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [?] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I would expect the theme to only load (plugin) scripts when they are needed.

It could be done with the method depicted in the attached .txt
[suggestion-for-only-loading-scripts-as-needed.txt](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/2356918/suggestion-for-only-loading-scripts-as-needed.txt)

# Current Behavior

It loads all scripts on all pages. Totally unnecessary and potentially this will create conflicts.

**Comment by groovemen** [comment]
Hello @LarsGMortensen, 

Thank you for using our products, we will clean the extra scripts that are unnecessary in the next product update. Best, Stefan
