### ISSUE TITLE
Original bootstrap-material-design.min.js file?

### ISSUE THREAD

**Issue by JAKgit** [creativetimofficial/ct-material-dashboard-pro#191]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

Where is the original bootstrap-material-design.min.js file? I would like to see what is all in there and modify it to suit our needs.

Thank you very much.

**Comment by JAKgit** [comment]
Anything?

**Comment by groovemen** [comment]
Hello @JAKgit, 

Thank you for your interest in working with our products, please check the following link: https://github.com/FezVrasta/bootstrap-material-design and download from their repo. 

All the best, 
Stefan

**Comment by JAKgit** [comment]
I have a pro developer license for over 200 USD is that the same file as the free version?

Thank you for your answer.
