### ISSUE TITLE
Collapsible icon don't rotate in v2.0.2 (worked in v2.0.1)

### ISSUE THREAD

**Issue by sfraysse** [creativetimofficial/ct-material-dashboard-pro#192]
# Prerequisites

Tested with Chrome.

# Expected Behavior

When collapsing or expanding a collapsible item, the arrow icon should rotate.

# Current Behavior

Does not work anymore in v2.0.2

# Steps to reproduce

1. Open the demo
2. Go to the Panels page
3. Play with the Accordion Panel

# Failure Information (for bugs)

Some CSS have been added in v2.0.2 which causes this issue.

```
a[data-toggle="collapse"][aria-expanded="true"] .caret,
a[aria-expanded="true"] .caret,
.dropdown.open .caret,
.dropup.open .caret,
.btn-group.bootstrap-select.open .caret,
.card-collapse .card-header a i {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2);
  -webkit-transform: rotate(180deg);
  -ms-transform: rotate(180deg);
  transform: rotate(180deg);
}
```

**Comment by groovemen** [comment]
Hello @sfraysse, 

Thank you for using our products, and also for your feedback; we will make an update this week and we'll solve this issue also. 

Best, 
Stefan
