### ISSUE TITLE
Feature Request: Dark mode

### ISSUE THREAD

**Issue by calebcall** [creativetimofficial/ct-material-dashboard-pro#193]
I noticed the free version now offers both a light and dark mode.  Is that feature coming to the pro version by chance?

**Comment by groovemen** [comment]
Hello @calebcall,
 
Thank you for your interest in working with our products, I will talk with my colleagues and probably in the near future, we will start the development for the PRO version of Black Material Dashboard. Appreciate your patience. 

All the best, 
Stefan
