### ISSUE TITLE
Unable to scroll in large modal

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-dashboard-pro#194]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I have a modal with a lot of content; I would expect to be able to scroll inside it - just like in the original Bootstrap design.

It would generally be best not to remove standard functionality from Bootstrap. I mean; yes, by all means, make it look good - but do not change the actual functionality.

# Current Behavior

Eventhough I copied code from getbootstrap.com to produce a large modal - which I was able to scroll inside on getbootstrap.com - I was NOT able to scroll in it when I loaded it inside your Material Dashboard Pro.
Please see this screencast-video: https://www.screencast.com/t/n2vdC4dd

**Comment by groovemen** [comment]
Hello @LarsGMortensen, 

Thank you for using our products, please let us know about your version that you are using on your project because I checked and everything looks good.

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/21063398/46200989-b69bd780-c31b-11e8-94e9-2a35d477dc18.gif)

All the best, 
Stefan

**Comment by LarsGMortensen** [comment]
Hi Stefan
Thank you for getting back to me about this.
I am running the latest version of the Dashboard Pro kit, in the latest version of Google Chrome, on a Windows PC.

I just tried it again - this time on your own demosite - and it is still not working, as you can see in this screencast video:
https://www.screencast.com/t/RrLu7PNN

Just to clarify:

- It is not working when I use the scroll-wheel on my mouse.
- But it is somehow working when I manually drag the scrollbar at the side of the window.
(as you can see in the abovementioned video)

Kind regards
Lars Mortensen

**Comment by groovemen** [comment]
Hello again, 

Please share with us a link to your project to make a quick check for your properties for the modal. 
Best, 
Stefan

**Comment by groovemen** [comment]
Hello again,

I found the solution that fixes the issue wich break the scroll for long content modals. All you have to do is to set the class **ps-child** into the modal: `<div class="modal ps-child">`. You could find the fix right here: https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/plugins/perfect-scrollbar.html 

Best, 
Stefan

**Comment by ArianulIslam** [comment]
This problem occurred for .perfect-scrollbar-on class in html tag. To solve this problem find & 
open material-dashboard.js file and comment out the $('html').addClass('perfect-scrollbar-on'); 
or change the class name to 'perfect-scrollbar-off' 
Don't forget to update the js version material-dashboard.js?v=2.1.2 to new version material-dashboard.js?v=2.1.3 to reset javascript version on your browser.
