### ISSUE TITLE
Adding buttons to Sidebar

### ISSUE THREAD

**Issue by rweller59** [creativetimofficial/ct-material-dashboard-pro#195]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I would like to add controls to the Sidebar. For example, adding slider switches below a navigation menu to control activity on the selected page. 

I really like the modular flexibility that you have provided with the menu structure and would like to maintain this flexibility with these additional controls.

Could you suggest a solution on where I might add this code?

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @rweller59,

Thank you for using our products, all you have to do is to add another <li> into your sidebar in which you will set a switch button and add a margin property to align it to the other items from the sidebar.

It will look like this:
<img width="259" alt="screenshot 2018-10-22 at 14 39 09" src="https://user-images.githubusercontent.com/21063398/47290456-47f32680-d608-11e8-9fc4-f88d9a1b02da.png">

All the best,
Stefan
