### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by ealbornoz** [creativetimofficial/ct-material-dashboard-pro#196]
Hello, I have two questions, I try to configure the DD-MM-YYYY format for the date selector, but I do not find how in the material, and the other is the date selector label is overlaid on the date value and it is necessary Put the mouse and press enter to fix it.

**Comment by groovemen** [comment]
Hello @ealbornoz, 

Thank you for using our products, being a third-party plugin I will ask you to check the following [link](https://stackoverflow.com/questions/4802190/how-do-i-format-date-in-jquery-datetimepicker) and see how to set a DD-MM-YYYY format for your datepicker. And related to the label that overlays the value of the input, I recommend you to erase the value attr. 

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
