### ISSUE TITLE
File Inputs not work

### ISSUE THREAD

**Issue by lyairmg** [creativetimofficial/ct-material-dashboard-pro#197]
Some examples of imputs file are presented in the documentation https://demos.creative-tim.com/material-dashboard-pro/docs/2.0/components/forms.html

```
<div class="form-group form-file-upload form-file-simple">
    <input type="text" class="form-control inputFileVisible" placeholder="Simple chooser...">
    <input type="file" class="inputFileHidden">
  </div>

  <div class="form-group form-file-upload form-file-multiple">
    <input type="file" multiple="" class="inputFileHidden">
    <div class="input-group">
        <input type="text" class="form-control inputFileVisible" placeholder="Single File">
        <span class="input-group-btn">
            <button type="button" class="btn btn-fab btn-round btn-primary">
                <i class="material-icons">attach_file</i>
            </button>
        </span>
    </div>
  </div>

  <div class="form-group form-file-upload form-file-multiple">
    <input type="file" multiple="" class="inputFileHidden">
    <div class="input-group">
        <input type="text" class="form-control inputFileVisible" placeholder="Multiple Files" multiple>
        <span class="input-group-btn">
            <button type="button" class="btn btn-fab btn-round btn-info">
                <i class="material-icons">layers</i>
            </button>
        </span>
    </div>
  </div>

```
In the documentation or when implementing do not work correctly

Note: when reviewing the Material Kit documentation the same example works correctly.

**Comment by shnabz** [comment]
Me too

**Comment by groovemen** [comment]
Hello, 

Thank you for using our products, I checked the problem and until the next update I will ask you to set the following code for inputs in the main JS file:

```
// FileInput
  $('.form-file-simple .inputFileVisible').click(function() {
    $(this).siblings('.inputFileHidden').trigger('click');
  });

  $('.form-file-simple .inputFileHidden').change(function() {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $(this).siblings('.inputFileVisible').val(filename);
  });

  $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
    $(this).parent().parent().find('.inputFileHidden').trigger('click');
    $(this).parent().parent().addClass('is-focused');
  });

  $('.form-file-multiple .inputFileHidden').change(function() {
    var names = '';
    for (var i = 0; i < $(this).get(0).files.length; ++i) {
      if (i < $(this).get(0).files.length - 1) {
        names += $(this).get(0).files.item(i).name + ',';
      } else {
        names += $(this).get(0).files.item(i).name;
      }
    }
    $(this).siblings('.input-group').find('.inputFileVisible').val(names);
  });

  $('.form-file-multiple .btn').on('focus', function() {
    $(this).parent().siblings().trigger('focus');
  });

  $('.form-file-multiple .btn').on('focusout', function() {
    $(this).parent().siblings().trigger('focusout');
  });
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by AppyCat** [comment]
Hi, I have tried the above JS code in my main JS file, and form submits fine, sends name of file, but not the data. I am using Material Kit PRO - v2.1.1

**Comment by slfan2013** [comment]
Material Dashboard PRO
V2.1.0 

Still has the same problem.

**Comment by groovemen** [comment]
Hello again, 

@AppyCat, in the Material Kit Pro, the Simple Material Inputs has the expected behavior (sending the file name but not the file). 

@slfan2013, I will ask you to send us a link to your project to check for a solution. I double checked and the code from above works fine. 

Best, 
Stefan

**Comment by AcidSlide** [comment]
check if the form tag has `enctype="multipart/form-data"`

**Comment by AcidSlide** [comment]
based on my testing the FileInput script does work, and make sure the form tag has `enctype="multipart/form-data"`

**Comment by rajivchaulagain** [comment]
I Got the Problem in the File Uploader in input. I used following code / Js and Implemented and It worked
//MAterial-customization
// FileInput
$('.form-file-simple .inputFileVisible').click(function() {
    $(this).siblings('.inputFileHidden').trigger('click');
  });

  $('.form-file-simple .inputFileHidden').change(function() {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $(this).siblings('.inputFileVisible').val(filename);
  });

  $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
    $(this).parent().parent().find('.inputFileHidden').trigger('click');
    $(this).parent().parent().addClass('is-focused');
  });

  $('.form-file-multiple .inputFileHidden').change(function() {
    var names = '';
    for (var i = 0; i < $(this).get(0).files.length; ++i) {
      if (i < $(this).get(0).files.length - 1) {
        names += $(this).get(0).files.item(i).name + ',';
      } else {
        names += $(this).get(0).files.item(i).name;
      }
    }
    $(this).siblings('.input-group').find('.inputFileVisible').val(names);
  });

  $('.form-file-multiple .btn').on('focus', function() {
    $(this).parent().siblings().trigger('focus');
  });

  $('.form-file-multiple .btn').on('focusout', function() {
    $(this).parent().siblings().trigger('focusout');
  });

**Comment by chakramani** [comment]
> I Got the Problem in the File Uploader in input. I used following code / Js and Implemented and It worked
> //MAterial-customization
> // FileInput
> $('.form-file-simple .inputFileVisible').click(function() {
> $(this).siblings('.inputFileHidden').trigger('click');
> });
> 
> $('.form-file-simple .inputFileHidden').change(function() {
> var filename = $(this).val().replace(/C:\fakepath\/i, '');
> $(this).siblings('.inputFileVisible').val(filename);
> });
> 
> $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
> $(this).parent().parent().find('.inputFileHidden').trigger('click');
> $(this).parent().parent().addClass('is-focused');
> });
> 
> $('.form-file-multiple .inputFileHidden').change(function() {
> var names = '';
> for (var i = 0; i < $(this).get(0).files.length; ++i) {
> if (i < $(this).get(0).files.length - 1) {
> names += $(this).get(0).files.item(i).name + ',';
> } else {
> names += $(this).get(0).files.item(i).name;
> }
> }
> $(this).siblings('.input-group').find('.inputFileVisible').val(names);
> });
> 
> $('.form-file-multiple .btn').on('focus', function() {
> $(this).parent().siblings().trigger('focus');
> });
> 
> $('.form-file-multiple .btn').on('focusout', function() {
> $(this).parent().siblings().trigger('focusout');
> });
Thank you for the solution.

**Comment by rajivchaulagain** [comment]
Note that Npm/Node has not been updated for Material kit v2.07

**Comment by rajivchaulagain** [comment]
> Hello,
> 
> Thank you for using our products, I checked the problem and until the next update I will ask you to set the following code for inputs in the main JS file:
> 
> ```
> // FileInput
>   $('.form-file-simple .inputFileVisible').click(function() {
>     $(this).siblings('.inputFileHidden').trigger('click');
>   });
> 
>   $('.form-file-simple .inputFileHidden').change(function() {
>     var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
>     $(this).siblings('.inputFileVisible').val(filename);
>   });
> 
>   $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
>     $(this).parent().parent().find('.inputFileHidden').trigger('click');
>     $(this).parent().parent().addClass('is-focused');
>   });
> 
>   $('.form-file-multiple .inputFileHidden').change(function() {
>     var names = '';
>     for (var i = 0; i < $(this).get(0).files.length; ++i) {
>       if (i < $(this).get(0).files.length - 1) {
>         names += $(this).get(0).files.item(i).name + ',';
>       } else {
>         names += $(this).get(0).files.item(i).name;
>       }
>     }
>     $(this).siblings('.input-group').find('.inputFileVisible').val(names);
>   });
> 
>   $('.form-file-multiple .btn').on('focus', function() {
>     $(this).parent().siblings().trigger('focus');
>   });
> 
>   $('.form-file-multiple .btn').on('focusout', function() {
>     $(this).parent().siblings().trigger('focusout');
>   });
> ```
> 
> Hope that information helps you. Please let us know if we can help you with anything else.
> 
> All the best,
> Stefan

Note that Npm/Node has not been updated for Material kit v2.07

**Comment by deepshila** [comment]
I got the same problem and this code worked for me. Thank you so much!!!!!!

**Comment by nmandeep26** [comment]
> I Got the Problem in the File Uploader in input. I used following code / Js and Implemented and It worked
> //MAterial-customization
> // FileInput
> $('.form-file-simple .inputFileVisible').click(function() {
> $(this).siblings('.inputFileHidden').trigger('click');
> });
> 
> $('.form-file-simple .inputFileHidden').change(function() {
> var filename = $(this).val().replace(/C:\fakepath\/i, '');
> $(this).siblings('.inputFileVisible').val(filename);
> });
> 
> $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
> $(this).parent().parent().find('.inputFileHidden').trigger('click');
> $(this).parent().parent().addClass('is-focused');
> });
> 
> $('.form-file-multiple .inputFileHidden').change(function() {
> var names = '';
> for (var i = 0; i < $(this).get(0).files.length; ++i) {
> if (i < $(this).get(0).files.length - 1) {
> names += $(this).get(0).files.item(i).name + ',';
> } else {
> names += $(this).get(0).files.item(i).name;
> }
> }
> $(this).siblings('.input-group').find('.inputFileVisible').val(names);
> });
> 
> $('.form-file-multiple .btn').on('focus', function() {
> $(this).parent().siblings().trigger('focus');
> });
> 
> $('.form-file-multiple .btn').on('focusout', function() {
> $(this).parent().siblings().trigger('focusout');
> });
> 
> //Note that You have to add enctype="multipart/form-data" in form tag

Thanks for sharing

**Comment by rajivchaulagain** [comment]
> I got the same problem and this code worked for me. Thank you so much!!!!!!
you're welcome If you are facing Any problems contact me 9881125552

**Comment by rajivchaulagain** [comment]
> I got the same problem and this code worked for me. Thank you so much!!!!!!

I got the same problem and this code worked for me. Thank you so much!!!!!!
you're welcome If you are facing Any problems contact me 9881125552

**Comment by rajivchaulagain** [comment]
> > I Got the Problem in the File Uploader in input. I used following code / Js and Implemented and It worked
> > //MAterial-customization
> > // FileInput
> > $('.form-file-simple .inputFileVisible').click(function() {
> > $(this).siblings('.inputFileHidden').trigger('click');
> > });
> > $('.form-file-simple .inputFileHidden').change(function() {
> > var filename = $(this).val().replace(/C:\fakepath/i, '');
> > $(this).siblings('.inputFileVisible').val(filename);
> > });
> > $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
> > $(this).parent().parent().find('.inputFileHidden').trigger('click');
> > $(this).parent().parent().addClass('is-focused');
> > });
> > $('.form-file-multiple .inputFileHidden').change(function() {
> > var names = '';
> > for (var i = 0; i < $(this).get(0).files.length; ++i) {
> > if (i < $(this).get(0).files.length - 1) {
> > names += $(this).get(0).files.item(i).name + ',';
> > } else {
> > names += $(this).get(0).files.item(i).name;
> > }
> > }
> > $(this).siblings('.input-group').find('.inputFileVisible').val(names);
> > });
> > $('.form-file-multiple .btn').on('focus', function() {
> > $(this).parent().siblings().trigger('focus');
> > });
> > $('.form-file-multiple .btn').on('focusout', function() {
> > $(this).parent().siblings().trigger('focusout');
> > });
> > //Note that You have to add enctype="multipart/form-data" in form tag
> 
> Thanks for sharing

Welcome Mandeep Sir

**Comment by deepshila** [comment]
> > I got the same problem and this code worked for me. Thank you so much!!!!!!
> 
> I got the same problem and this code worked for me. Thank you so much!!!!!!
> you're welcome If you are facing any problems contact me 9881125552

surely if I got any problem I will reach out to you !!!!!!!
