### ISSUE TITLE
error on template

### ISSUE THREAD

**Issue by dguimard** [creativetimofficial/ct-material-dashboard-pro#198]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

working
# Current Behavior
material-dashboard.min.js?v=2.0.2:1 Uncaught TypeError: Cannot read property 'outerHTML' of undefined
    at Object.<anonymous> (material-dashboard.min.js?v=2.0.2:1)
    at material-dashboard.min.js?v=2.0.2:1

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

just refresh the template page from the given product.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @dguimard, 

Thank you for using our products, I will ask you to use the normal JS file (not the minified one) and let us know if it has the same behavior. I checked in the user's downloadable archive and everything looks good.

Best, 
Stefan
