### ISSUE TITLE
Cannot change color on Calendar buttons

### ISSUE THREAD

**Issue by mrwadepro** [creativetimofficial/ct-material-dashboard-pro#199]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by mrwadepro** [comment]
I cannot figure out how to change the button colors on the Calendar in the dashboard? I changed the primary colors and all the other colors in the `material-dashboard-pro-react`, but it's still purple. Where do I go to change the colors?

**Comment by groovemen** [comment]
Hello @mrwadepro, thank you for using our products, I will ask you to let us know about your product type (e.g. HTML, React..) also the version that you're using.
Best, 
Stefan
