### ISSUE TITLE
Many double styles

### ISSUE THREAD

**Issue by pukdata** [creativetimofficial/ct-material-dashboard-pro#200]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I expect a clean styling and single styles

# Current Behavior

Many styles are double. Massive unnecessary loading of double style. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. check for example:
material-dashboard-pro-html-v2.0.2\assets\scss\material-dashboard\plugins\_plugin-bootstrap-select.scss

2. Almost complete code is double

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @pukdata,
Thank you for using our products and for your feedback we will fix this issue into the next update. Sorry for the inconvenience. Best, Stefan
