### ISSUE TITLE
Bug when I use Jquery on change event and material-dashboard.js

### ISSUE THREAD

**Issue by israellias** [creativetimofficial/ct-material-dashboard-pro#201]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

When I updated my template to material dashboard pro 2.0.2 I found an issue and I tested on your demo and this is the result. 
![oct-18_-2018-10_23-am](https://user-images.githubusercontent.com/16140960/47164229-9f6e5b00-d2c5-11e8-81c3-78f91228821a.gif)

I just added the following code at line 1080
![image](https://user-images.githubusercontent.com/16140960/47164839-c6795c80-d2c6-11e8-8f96-37dffed1a77e.png)

# Failure Information (for bugs)

All my jquery events are failing now, and they are slowing down the browser. I found this error specifically in material-dashboard.js file. 

## Context

Jquery

**Comment by israellias** [comment]
I've debugged this and I found the fail is here. 
it happen because at begin the inputs don't have the 'value' attr defined on itself. So undefined is not equal to "" empty string and that triggers the change event.
 
![image](https://user-images.githubusercontent.com/16140960/47179296-b88a0280-d2eb-11e8-86e9-ccf2cbcec0ed.png)

I did a monkey patch here. But what would be a better solution?

**Comment by compuetrking** [comment]
Same Issue when I input any value in foam text box as above..

**Comment by groovemen** [comment]
Hello @israellias, thank you for using our products, as you can see in the photo that you have attached above, the problem is from the **bootstrap-material-design.js** file. We will make an update this week for this product and we also make an update to the bootstrap library. 

All the best, 
Stefan
