### ISSUE TITLE
Horizontal timelines.

### ISSUE THREAD

**Issue by somada141** [creativetimofficial/ct-material-dashboard-pro#202]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

Hi there, I would like to display a timeline much like the one shown under the `WidgetsComponent` but horizontally arrayed. From what I gather timelines using the provided are explicitly vertical. Would you happen to have an equivalent for horizontal timelines or advise on how to amend the existing one to make it horizontal?

**Comment by groovemen** [comment]
Hello @somada141, 
Thank you for using our products, unfortunately, we don't have an example with a horizontal timeline but here are some examples: 
- https://codepen.io/jessyca27/pen/vGoBex
- https://codepen.io/kjohnson/pen/azBvaE 
- https://codyhouse.co/demo/horizontal-timeline/index.html

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
