### ISSUE TITLE
Material design form elements do not behave well in IE11

### ISSUE THREAD

**Issue by basmbbl** [creativetimofficial/ct-material-dashboard-pro#204]
The placeholders are gone after clicking the input field, animation of the bottom line is missing. 
Example: https://demos.creative-tim.com/material-kit-pro/examples/login-page.html
![screenshot2](https://user-images.githubusercontent.com/20164457/47342397-e7b1c280-d6a3-11e8-93a8-99dc08fc0b16.PNG)

**Comment by groovemen** [comment]
Hello @basmbbl, thank you for using our products, unfortunately, we don't offer support for the IE11, as you can see in the readme: https://github.com/creativetimofficial/ct-material-dashboard-pro#browser-support 


Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
