### ISSUE TITLE
Align bmd-label-floating to the right

### ISSUE THREAD

**Issue by idon14** [creativetimofficial/ct-material-dashboard-pro#205]
There is no way currently to align the `bmd-label-floating` to the right. 
The input text is aligned to the right, but the label isn't.
I've tried to align it with `text-align: right`, `float: right`, `pull-right` class, but so far nothing has worked.

Below, you can see what the label looks like with and without input.

<img width="526" alt="screen shot 2018-11-10 at 23 48 56" src="https://user-images.githubusercontent.com/18172749/48306573-78f9b380-e543-11e8-8205-3f9540f83260.png">

<img width="533" alt="screen shot 2018-11-10 at 23 49 09" src="https://user-images.githubusercontent.com/18172749/48306574-7dbe6780-e543-11e8-8510-c47b5dbc8571.png">

**Comment by groovemen** [comment]
Hello @idon14,

Thank you for using our products, all you have to do for having the `bmd-label-floating` aligned to the right is to set the following properties for the bmd-label-floating class:

```
.bmd-label-floating {
   text-align: right;
   position: absolute;
   right: 0;
}
```

Then it will look like this: 
<img width="579" alt="screenshot 2018-11-22 at 10 53 31" src="https://user-images.githubusercontent.com/21063398/48891916-65a0ef00-ee45-11e8-9d74-f2130028fc5c.png">
<img width="571" alt="screenshot 2018-11-22 at 10 53 45" src="https://user-images.githubusercontent.com/21063398/48891917-65a0ef00-ee45-11e8-8829-77bb40f45324.png">

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
