### ISSUE TITLE
Upgrade to 2.1 version

### ISSUE THREAD

**Issue by ndmuratsahin** [creativetimofficial/ct-material-dashboard-pro#207]
Hi,
Normally I am using Pro version 2.0.2. How can I upgrade to 2.1 on my existing project ? Is it enough to replace js and css files? could you more information about upgrading? 

On the other hand I can't reach 2.0.2 documentation. The link is broken.

**Comment by groovemen** [comment]
Hello @ndmuratsahin,
 
Thank you for using our products, to update your product to 2.1.0 version you have to replace only the JS and CSS(scss) files with the new ones. And copy the error page from `example/pages/error.html` only if you'll need [it](https://demos.creative-tim.com/material-dashboard-pro/examples/pages/error.html). The new documentation link is: https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/getting-started/introduction.html but we will fix the old docs link thanks to you 😄

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by ndmuratsahin** [comment]
Thanks @groovemen
