### ISSUE TITLE
Long Modal Scroll Issue

### ISSUE THREAD

**Issue by LauKL1991** [creativetimofficial/ct-material-dashboard-pro#208]
Hello,

I had been using your Pro version product since last month. Currently I found the issue when scroll a large/long modal, it scroll the background instead of the modal itself. How to fix this issue?

Below is the video link:
===========================
https://drive.google.com/file/d/1PmzCEhqpdqfOhT9S7RJNW7ZdGz2fnxfD/view

**Comment by groovemen** [comment]
Hello @LauKL1991,

Thank you for using our products, I reproduced this issue in the livePreview an also in user's downloadable archive but everything looks good. Please let us know what OS and browser you are using and maybe you can share with us a link to your project to check for the problem.

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/21063398/48891534-46ee2880-ee44-11e8-803d-85fec81b397b.gif)

All the best, 
Stefan

**Comment by LauKL1991** [comment]
Hello,

I am using Windows 10 and Google Chrome. 

Below is the link
==========================
https://dev.geniqtech.com/examples/components/notifications.html

**Comment by groovemen** [comment]
Hello again,

I found the solution that fixes the issue wich break the scroll for long content modals. All you have to do is to set the class **ps-child** into the modal: `<div class="modal ps-child">`. You could find the fix right here: https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/plugins/perfect-scrollbar.html 

Best, 
Stefan

**Comment by LauKL1991** [comment]
Hello,

Thanks for your information. It seem fixed but when i want to use select option in modal, it doesnt work.

Link
====================
https://dev.geniqtech.com/examples/components/notifications.html

#The classic modal button
