### ISSUE TITLE
sidebar background-color red 

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/ct-material-dashboard-pro#21]
Here in the bottom I will attach the modified partial `_sidebar-and-main-panel.scss` for having background-color red on sidebar. You must overwrite this file with the partial located in `assets/_scss/material-dashboard/_sidebar-and-main-panel.scss`, and if you have modified something in your file you must merge the old file with the new one. After you overwrite you must follow the next steps: 

1.  First you must compile you Scss with [Koala](http://koala-app.com/).

2. Second to change your color you must open the html page that you want from` examples` folder, then find the attribute `data-background-color` and `data-active-color` from the div with class `.sidebar` and just change the value of this attribute with `"red"` and also change the value of `data-active-color` with `white`.

[_sidebar-and-main-panel.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/850631/_sidebar-and-main-panel.scss.zip)

**Comment by genievn** [comment]
Wow, you guys rock !

That's exactly what I want, perfect ! Thank you for quick response!

Br,
