### ISSUE TITLE
datatables button dropdown not show.

### ISSUE THREAD

**Issue by php143** [creativetimofficial/ct-material-dashboard-pro#213]
![image](https://user-images.githubusercontent.com/9420325/49693627-478afc80-fb70-11e8-9a39-cab48b69b2d4.png)

datatables.net dropdown menu not show,

**Comment by groovemen** [comment]
Hello @php143,

Thank you for using our products, please provide us more details about your issue or I just share with us a link to your project to find a solution. 

**you can try to change the background-color for the `navbar-toggler-icon`

All the best, 
Stefan

**Comment by shrestharikesh** [comment]
![colvis](https://user-images.githubusercontent.com/25215978/53221863-802c7380-3693-11e9-8cbb-94e728cf5b1f.jpg)
colivs button dropdown is not working.

**Comment by groovemen** [comment]
Hello @shrestharikesh,

Thank you for using our products, I will ask you to share with us a link to your project to help you identify the problem. 

Best, 
Stefan

**Comment by shaileishrana** [comment]
Hi , Is the above issue fixed? Because I am getting the same issue in Datatables .
The Column Visibility button in Datatables is not working in material dashboard pro 2.1.0
Not getting any columns to select/de-select.
Kindly advise.
Rgds,
Shaileish

**Comment by Jam3si** [comment]
Same here, I tried to update DataTables plugin but no luck there. It seems like something in MaterialDashboard css is blocking the dropdown when buttons like 'colvis' and 'pageLength' are used.

**Comment by php143** [comment]
hi,
sorry for late reply.
here i found some solution that work for me.
![dropdown](https://user-images.githubusercontent.com/9420325/55573125-db3b9680-5726-11e9-86b1-0a62e5ce62c7.png)

**Comment by shaileishrana** [comment]
@php143 Thank you for your reply, this fix worked for me too.

Rgrds,
Shaileish

**Comment by Jam3si** [comment]
Not sure this is the best solution, but worked for me as well. Thank you @php143 :) Hope @groovemen will fix it in next release
