### ISSUE TITLE
broken sidebar and console errors (sidebar roto y errores de consola)

### ISSUE THREAD

**Issue by elias442** [creativetimofficial/ct-material-dashboard-pro#214]
# Prerequisites
Please answer the following questions for yourself before submitting an issue.

[ yes] I am running the latest version
[ yes] I checked the documentation and found no answer
[ yes] I checked to make sure that this issue has not already been filed
[yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

### Expected Behavior

![image](https://user-images.githubusercontent.com/12775736/49754124-0e4bad00-fc94-11e8-81a8-ad50d822aec7.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/12775736/49754237-4d79fe00-fc94-11e8-8ed5-fb1756ae3c36.png)

![image](https://user-images.githubusercontent.com/12775736/49754281-6d112680-fc94-11e8-9524-f7577f5c834f.png)

### **The mobile menu does not work, the desktop menu does not work as well, and I have this console error.**

**Comment by groovemen** [comment]
Hello @elias442,

Thank you for using our product, I will ask you to give us more details about your issues and also share with us a link to your project to look for a solution. It's hard to figure out what's going on with your sidebar as long as in the livePreview and in the user's archive, it's working fine. 

Best, 
Stefan

**Comment by elias442** [comment]
**Este es el código (This is code):** https://github.com/BrannAR/Enli

**Comment by elias442** [comment]
Is code it's found in: /admin

**Comment by groovemen** [comment]
Hello again @elias442, 

Thank you for using our products, I will ask you to change your **footer.php** from admin with this one:  
```
<footer>

</footer>
<!-- BOOTSTRAP -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!-- PLUGINS -->
<script src="vendor/js/plugins/arrive.min.js"></script>
<script src="vendor/js/plugins/bootstrap-notify.js"></script>
<script src="vendor/js/plugins/chartist.min.js"></script>
<script src="vendor/js/plugins/jquery.dataTables.min.js"></script>
<script src="vendor/js/plugins/jquery.validate.min.js"></script>
<script src="vendor/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<script src="vendor/js/plugins/sweetalert2.js"></script>
<!-- TEMPLATE -->
<script src="vendor/js/material-dashboard.min.js"></script>
```

All the best, 
Stefan

**Comment by elias442** [comment]
Thanks :)
