### ISSUE TITLE
Background image not displaying

### ISSUE THREAD

**Issue by digiscribe** [creativetimofficial/ct-material-dashboard-pro#216]
Hi, I'm just starting to use the template for the first time.  It is very well done.

I have a question about the background image for page.  In order for the background image to show, I have to include the:  /js/demo.js, which has the comment that says "don't include it in your project".

Is there something else I should be doing?

Thank you.

**Comment by groovemen** [comment]
Hello @digiscribe, 

Thank you for using our products, I will ask you to be more specific; what page has this problem and also please make sure that the route to your image is correct. The **demo.js** file has nothing to do with the image displaying.

Waiting for your answer. Please let us know if we can help you with anything else.

All the best, 
Stefan

**Comment by digiscribe** [comment]
Thank you for the response.  I just tested it again multiple times to confirm.  I am using the login page.  The path to the image is definitely correct.  When I remove the demo.js file, the background image does not display, when I add it back, it displays correctly.

**Comment by digiscribe** [comment]
FWIW, I realized that the js on the bottom of the page also refers to the demo:

demo.checkFullPageBackgroundImage();

Maybe I just need to change this?

**Comment by groovemen** [comment]
Hello again @digiscribe,

You have to move the `checkFullPageBackgroundImage()` function from **demo.js** file to **material-dashboard.js** into the `md = {...}; object`. Please let us know what version of the product are you using because in the last one the function from above is already moved.

Best, 
Stefan
