### ISSUE TITLE
Modal Scroll Issue

### ISSUE THREAD

**Issue by LauKL1991** [creativetimofficial/ct-material-dashboard-pro#217]
Hello @groovemen ,

There is an issue when I try to use the select option in modal, it doesn't work. The scroll doesn't apply to the select option, instead, it scrolls the whole page.

Link
https://dev.geniqtech.com/examples/components/notifications.html
#The **classic modal** button

Also, there is another issue on the datetimepicker, it will randomly throw the error: 

> Uncaught TypeError: h.remove is not a function at bootstrap-datetimepicker.min.js:47

When I try to change the js with the latest CDN, the datetimepicker doesn't work. 

Please help to fix, thanks.

**Comment by elias442** [comment]
Hello @LauKL1991 
I will ask you to change your footer with this one:

`<footer>

</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="vendor/js/plugins/arrive.min.js"></script>
<script src="vendor/js/plugins/bootstrap-notify.js"></script>
<script src="vendor/js/plugins/chartist.min.js"></script>
<script src="vendor/js/plugins/jquery.dataTables.min.js"></script>
<script src="vendor/js/plugins/jquery.validate.min.js"></script>
<script src="vendor/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<script src="vendor/js/plugins/sweetalert2.js"></script>

<script src="vendor/js/material-dashboard.min.js"></script>`

And then tell me if it worked

**Comment by elias442** [comment]
Reorganize the directories as I did, remove the components as I did in this repository
#214 

https://github.com/BrannAR/Enli/tree/master/admin

**Comment by LauKL1991** [comment]
Hello @elias442 ,

Thanks for the reply. Look on the attached photo, currently, I set the sequence like this but still doesn't work.


![image](https://user-images.githubusercontent.com/45256398/50500895-3f4b2080-0a8f-11e9-8d41-07a09cf8e4f1.png)

**Comment by groovemen** [comment]
Hello @LauKL1991,

Thank you for using our products, I will ask you to give us more details about your OS and try to update to the latest version. I also checked the link with your project and it looks good:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21063398/50640182-c0f9ed00-0f6c-11e9-8cdf-34af68990d82.gif)

All the best, 
Stefan

**Comment by LauKL1991** [comment]
@groovemen 

Thanks for your reply. The attached image is the details.

![capture](https://user-images.githubusercontent.com/45256398/50668679-825f4380-0ffb-11e9-90fb-603323592907.PNG)

**Comment by groovemen** [comment]
Hello again, 

Did you try to initialize the `perfectScrollbar()` for the **selectpicker** class ?! 

try to add in the material-dashboard.js file like this: 

<img width="805" alt="screenshot 2019-01-10 at 16 15 27" src="https://user-images.githubusercontent.com/21063398/50974330-ab983c00-14f3-11e9-87b6-5e8cda347a29.png">

Best, 
Stefan

**Comment by LauKL1991** [comment]
Hello,

Are you mean to initialize like this? 

>  <script> 
  $(document).ready(function() {
    // Javascript method's body can be found in assets/js/demos.js
    md.initDashboardPageCharts();
    md.initVectorMap(); 
     (function () {
    isWindows = navigator.platform.indexOf('Win') > -1 ? true:false;
    if(isWindows){
      $('.sidebar .sidebar-wrapper, .main-panel, .selectpicker').perfectScrollbar();
      $('html').addClass('perfect-scrollbar-on');
    }
    else{
      $('html').addClass('perfect-scrollbar-off');
    }
  })();
  });
  </script>

**Comment by groovemen** [comment]
No, you just have to add the class **.selectpicker** into that function from **material-dashboard.js** file

**Comment by LauKL1991** [comment]
Hello,

I had added, and the problem still there, even worst. The drop-down menu unable to show. You can check on the link.

Link
https://dev.geniqtech.com/examples/components/notifications.html
#The classic modal button

**Comment by LauKL1991** [comment]
Hello,

Any update on this issue?

Thanks

**Comment by groovemen** [comment]
Hello,

I checked your main JS file and I don't find the selectpicker class to be presented in the initialization of the perfectScrollbar.

<img width="870" alt="screenshot 2019-01-17 at 13 59 23" src="https://user-images.githubusercontent.com/21063398/51317438-3d59f900-1a60-11e9-9871-131efdd1b632.png">

Please make those changes and let us know if it worked.

Best

**Comment by LauKL1991** [comment]
Hello, 

Actually, I did add, but I removed recently since it broke the select option. I will add it back now.

**Comment by LauKL1991** [comment]
Hello,

Is the issue can be fixed?

Thanks.
