### ISSUE TITLE
Date of error if you use multiple dates

### ISSUE THREAD

**Issue by hendrahe2885** [creativetimofficial/ct-material-dashboard-pro#219]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
date runs normally if many dates

# Current Behavior

blank date when many dates appear

# Failure Information (for bugs)

when I retrieve date data from a database with lots of dates, then a lot of dates are blank (I can't take many dates)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
```
<div class="input-group date" data-provide="datepicker" data-date-format="dd-mm-yyyy">
<input type="text" name="tanggal_<?php echo $no;?>" class="form-control datepicker" maxlength="10" value="<?php if($data[$i]['tgl_pertemuan']==0000-00-00){
echo date('d-m-Y'); }else if ($mode=="EDIT") echo date('d-m-Y',strtotime($data[$i]['tgl_pertemuan'])); ?>" required autofocus>
</div>
```

More Page

```
<tr>
<td>3</td>
<td>Batas Tanggal Kontrak Praktikum</td>
<td>
<div class="form-group">
<div class="input-group date" data-provide="datepicker" data-date-format="dd-mm-yyyy">
<input type="text" class="form-control datepicker" name="batas_input_krp" value="<?php echo date('d-m-Y', strtotime($data[0]['batas_input_krp'])); ?>" required autofocus>
<div class="input-group-addon">
<input type="hidden" id="batas_input_krp" value="" />
</div>
</div>
</div>
</div>
</td>
</tr>
<td>4</td>
<td>Masa Input Pertemuan</td>
<td>
<div class="col-md-6">
<div class="form-group">
<input type="text" class="form-control datepicker" name="tanggal_input_rps" value="<?php echo date('d-m-Y', strtotime($data[0]['tanggal_input_rps'])); ?>" required autofocus>
 </div>
<input type="hidden" id="tanggal_input_rps" value="" />
</div>
</div>
<div class="col-md-6">
<div class="form-group">
<input type="text" class="form-control datepicker" name="batas_input_rps" value="<?php echo date('d-m-Y', strtotime($data[0]['batas_input_rps'])); ?>" required autofocus>
<div class="input-group-addon">
<span class="glyphicon glyphicon-th"></span>
<input type="hidden" id="tanggal_lahir" value="" />
</div>
</div>
</div>
</td>
</tr>
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Macbook Air
* Operating System: MacOS 10.14.2 (Mojave)
* Browser and Version: Chrome 71.0.3578.98 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.
![screen shot 2019-01-13 at 09 09 41](https://user-images.githubusercontent.com/15024348/51080699-43c03c00-1713-11e9-978b-c8e13ea0fdc2.png)
![screen shot 2019-01-13 at 09 11 04](https://user-images.githubusercontent.com/15024348/51080700-43c03c00-1713-11e9-9d6b-d2b44a082a12.png)

**Comment by smohannagaraj** [comment]
Use Google chrome inspector tool to find which css is creating this.
I think:
1. The code which you used to create a table has a error.  You can use online code checkers. OR
2. You are using another css with material-kit-pro

**Comment by groovemen** [comment]
Hello @smohannagaraj,

We are very sorry for this late response, by mistake I missed this opened issue. Please let us know if you figured out. 

Please let us know if we can help you with anything else.

All the best,
Stefan
