### ISSUE TITLE
Select Option JQuery Validation No Error Message display

### ISSUE THREAD

**Issue by LauKL1991** [creativetimofficial/ct-material-dashboard-pro#221]
Hello,

I had tried to add validation to the select option. It does validate and doesn't allow to proceed to the next step (form wizard), but, there is no **red line** or **error message** to indicate the field is required to select.

**Comment by groovemen** [comment]
Hello @LauKL1991,

Thank you for using our products, all you have to do is to set for you validation function the following: 
```
errorPlacement : function(error, element) {
       $(element).closest('.form-group').append(error);
 }
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by LauKL1991** [comment]
Thanks very much!!
