### ISSUE TITLE
Found a Bug in navbar > container IE 11

### ISSUE THREAD

**Issue by zetser** [creativetimofficial/ct-material-dashboard-pro#222]
container in navbar is not centered when use IE 11

![2019-01-29 11_24_18-material dashboard pro by creative tim - internet explorer](https://user-images.githubusercontent.com/6279025/51927138-7d9e6d00-23b8-11e9-81a0-f12fbe6fa9b3.png)

Just add this in _navbar.scss, line 126

> .container {
        flex: 1 0 0;
        -ms-flex: 1 0 0;
    }

**Comment by groovemen** [comment]
Hello @zetser, 

Thank you for using our products and for your solution; unfortunately, we don't offer support for the IE browser: https://github.com/creativetimofficial/ct-material-dashboard-pro#browser-support .

Thank you for your understanding. 
All the best, 
Stefan
