### ISSUE TITLE
wizard from issue, wizard from dose not work in rtl layout

### ISSUE THREAD

**Issue by zhyarmRasul** [creativetimofficial/ct-material-dashboard-pro#223]
I tried wizard form in rtl layout, but the direction dosent chane and not working

**Comment by groovemen** [comment]
Hello @zhyarmRasul, 

Thank you for using our products, unfortunately, we don't set the wizard for the RTL page so you have to create the style for it. I will talk with my colleagues and maybe we will integrate into the next update.

Sorry for the inconvenience.
All the best, 
Stefan

**Comment by zhyarmRasul** [comment]
thank you bro... @groovemen
