### ISSUE TITLE
rtl in pro version not working well, for example forms, the free version works well

### ISSUE THREAD

**Issue by goyuval3** [creativetimofficial/ct-material-dashboard-pro#225]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @goyuval3, 

Thank you for using our products, I will ask you to provide more details about this issue.
Waiting for your issue. 

Best, 
Stefan

**Comment by goyuval3** [comment]
look at the example.
i bought the pro version because the rtl  was great. whats is the point if i need to go through the css myself now?

![pro](https://user-images.githubusercontent.com/13410073/52966366-c2ae3180-33af-11e9-8eaa-9b4473b393fc.gif)

**Comment by goyuval3** [comment]
another example

![pro1](https://user-images.githubusercontent.com/13410073/53006927-ea000f80-343e-11e9-84d8-b761d0e7c8b5.gif)
