### ISSUE TITLE
How can I add left and right sidebar

### ISSUE THREAD

**Issue by Srtt** [creativetimofficial/ct-material-dashboard-pro#227]
I want to add new sidebar to the right .. so I want to use left and right sidebar ..
How can I add it quickly .. ?
pro version..

**Comment by groovemen** [comment]
Hello @Srtt,

Thank you for using our products, you can change the sidebar from right to left only on responsive by adding **class="menu-on-left"** on the body tag. 

Best, 
Stefan

**Comment by Srtt** [comment]
Hello again @groovemen ,
I want to add new one on right side so I want to use 2 sidebar

**Comment by groovemen** [comment]
So you have to check the style for the RTL page (having the sidebar on right) https://demos.creative-tim.com/material-dashboard-pro/examples/pages/rtl.html
