### ISSUE TITLE
Problem with select

### ISSUE THREAD

**Issue by ghten** [creativetimofficial/ct-material-dashboard-pro#229]
I have a problem with select when I open my page

Code: 
 ```
 `<div class="form-group bmd-form-group dropdown bootstrap-select show-tick dropup">
<select class="form-control" formControlName="country" class="selectpicker" data-style="btn btn-link">
<option selected="selected"></option>
<option value="1">toto</option>
</select>
</div>
```
`
Result
![select](https://user-images.githubusercontent.com/45689669/54426555-750bb700-4718-11e9-92e5-6acd38c267a6.png)

I don't see the select, just label
Thanks

**Comment by groovemen** [comment]
Hello @ghten,

Thank you for using our products, I will ask you to give us a link to your project. This is the structure that you have used for the selectpicker? Waiting for your answer.

Best, 
Stefan
