### ISSUE TITLE
In need bootstrap-material-design.js not minify js

### ISSUE THREAD

**Issue by sahilbabu** [creativetimofficial/ct-material-dashboard-pro#230]
Hi Creative Tim team [@ghten @Srtt, @groovemen]
I already purchased the pro version of "Material Dashboard Pro".
I need bootstrap-material-design.min.js as un-minify js so that I can extend it according to my project usage. Thanks

**Comment by groovemen** [comment]
Hello @sahilbabu, 

Thank you for your interest in working with our products, please check the official page of Bootstrap Material Design: https://fezvrasta.github.io/bootstrap-material-design/ 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by bbuehrle** [comment]
Just for verification... does this mean that the `bootstrap-material-design.min.js` file that is included has no alterations from creative-tim?

**Comment by groovemen** [comment]
@bbuehrle, please read the description of the README: https://github.com/creativetimofficial/ct-material-dashboard-pro 
Material Dashboard PRO is a Premium Material Bootstrap 4 Admin with a fresh, new design inspired by Google's Material Design. It is based on the popular Bootstrap 4 framework and comes packed with multiple third-party plugins. All components are built to fit perfectly with each other, while aligning to the material concepts.

Cheers,
Stefan

**Comment by alexwenbj** [comment]
Uh,I still don't understand,I have the same question as @sahilbabu ,I have purchased the creative tim's material PRO version,and still can't get the  javascript code to extend it?For example, get and set the sidebar settings(e.g. mini sidebar/background image/background color)?

**Comment by sahilbabu** [comment]
Could you please provide 
│   ├── js/
│   │   ├── core/
│   │   │   ├── bootstrap-material-design.min.js

Unminify version of bootstrap-material-design.min.js 
or it just includes jquery.min.js, popper.min.js ?

**Comment by groovemen** [comment]
It looks like you cannot download it from the Official Page?! Is there a problem? 
Here you go: [bootstrap-material-design.js.zip](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/3019074/bootstrap-material-design.js.zip)
Please let us know if we can help you with anything else.

**Comment by sahilbabu** [comment]
thanks, @groovemen for your great help!
