### ISSUE TITLE
Bug in navigation Edge only: large distances between list items

### ISSUE THREAD

**Issue by tillito77** [creativetimofficial/ct-material-dashboard-pro#231]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version (2.1.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The navigation on the left should look the same on all browsers.

# Current Behavior

Sometimes (most of the times) in Edge there is too much space between the items in the 2nd level navigation. Please check the attached image:

![spaceproblem](https://user-images.githubusercontent.com/12332612/56436963-fccb7f00-62dd-11e9-9d69-2968783f7a89.PNG)

# ADDED 16th July 2019

I uploaded your template to my windows server. The problem is reproducable. Please check:

http://aaarbeit2.papepape.de/material-dashboard-pro/examples/dashboard.html

![grafik](https://user-images.githubusercontent.com/12332612/61303100-39c4e600-a7e7-11e9-9d5e-525879d87dbb.png)

# Failure Information (for bugs)

Weirdly, this only occurs in my local version http://local.aaarbeit2/material-dashboard-pro/examples/components/panels.html. And even there, around 4 of 5 page loads the error occurs, in 1 of 5 loads all looks fine in edge. When I load http://local.aaarbeit2/material-dashboard-pro/examples/components/panels.html in edge, the spaces are always correct.

Are you sure, that your demo page and the latest version (2.1.0) are identical? I did not change anything after the download.

Before, I used the version 2.0.2. The error occured here, too. Actually, the reason for my update was the hope that the error would be fixed in 2.1.0.

## Context

Latest version of Edge. Using your download 2.1.0 as it is, without compiling the bundels etc.

* Device: PC
* Operating System: Windows 10 Pro
* Browser and Version: Edge 42.17134.1.0
* Host: IIS 10

## Premium support

Yes, I have premium support. See my email com@till-pape.de.

**Comment by tillito77** [comment]
@groovemen , why did you close this ticket? Is it fixed? Please explain.

**Comment by groovemen** [comment]
Hello @tillito77,

Thank you for using our products, I am really sorry  I closed it by mistake, I also checked this behavior on many OS and different browsers, but it works as expected. Also, the localhost links that you mentioned above didn't work. I will ask you to recreate the links to let us check it for finding a solution. 

Best, 
Stefan

**Comment by tillito77** [comment]
I updated the ticket. The problem is reproducable. Sometimes, Edge shows the spaces correcly. If it does, just reload the page with F5 and you will see the problem, sooner or later.

**Please re-open ticket.**

**Comment by tillito77** [comment]
I think the bug has to do with the animation. The final state seems to calculate the position (not the margin) wrong. This is at least my closest guess.

**Comment by groovemen** [comment]
Hello again, 

I tried many times to get to this behavior that you faced but unfortunately, after many refreshes(F5) on Edge, I cannot reach the issue that you presented above (even on your shared link).  
![67377707_319466108938246_7360128989496606720_n](https://user-images.githubusercontent.com/21063398/61306006-8105a380-a7f4-11e9-889b-72d464e4e805.jpg).

Maybe if I can inspect element to see what's happening I can help you.

Best, 
Stefan

**Comment by tillito77** [comment]
![grafik](https://user-images.githubusercontent.com/12332612/61309061-cffe0980-a7f1-11e9-9492-43a117c9939a.png)

Hm, strange. This is my version of edge. And using Windows 10, latest version.

It is also reproducable on a 2nd computer with the same configuration.

**Comment by tillito77** [comment]
Since the latest Windows-Update, this error does not show any more on any of our test systems. I think it was a bug in Edge which has been solved.

**Comment by groovemen** [comment]
We are glad to hear that. Keep up the good work!

All the best, 
Stefan
