### ISSUE TITLE
Visual Studio Bundle - Minification failed

### ISSUE THREAD

**Issue by hongz1** [creativetimofficial/ct-material-dashboard-pro#235]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Visual Studio should bundle with other stylesheets and minify them without any issues

# Current Behavior

material-dashboard.css and even minified files are not able to be bundled due to minification failure.

# Failure Information (for bugs)

/* Minification failed. Returning unminified contents.
(11346,29): run-time error CSS1030: Expected identifier, found '['
(11346,34): run-time error CSS1031: Expected selector, found '='
(11346,34): run-time error CSS1025: Expected comma or open brace, found '='
(29280,1): run-time error CSS1019: Unexpected token, found '}'
 */
/*!

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compiled Visual Studio 2017 Community edition and opened Edge and Chrome browsers
2. Went to debug section in developer tool window and checked bundled css
3. bundled css file was not minified and the message above was shown.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Dell laptop
* Operating System: Windows 10
* Browser and Version: Chrome 74.0.3729.157 (Official Build) (64-bit)
                                     Microsoft Edge:  44.17763.1.0

## Failure Logs

/* Minification failed. Returning unminified contents.
(11346,29): run-time error CSS1030: Expected identifier, found '['
(11346,34): run-time error CSS1031: Expected selector, found '='
(11346,34): run-time error CSS1025: Expected comma or open brace, found '='
(29280,1): run-time error CSS1019: Unexpected token, found '}'
 */
/*!

**Comment by groovemen** [comment]
Hello @hongz1, 

Thank you for using our products, you can try to minify your file using this online tool to see if it's working: https://cssminifier.com/

Best, 
Stefan
