### ISSUE TITLE
Color configuration

### ISSUE THREAD

**Issue by Qvatra** [creativetimofficial/ct-material-dashboard-pro#237]
I'm not sure that this is a bug or is done by design but I think I need a little bit more explanation how color system works in this theme.

Just a bit of explanation of how your template is used:
Your sass theme solution is fully integrated in our project and is instantly recompiled by webpack on a file change. This was done to speed up the process of adjusting the theme to our needs. At the same time we are keeping theme files separately and intact so it would be possible to update the theme to the latest later.

in _brand.scss variables file I can find:
```
$brand-primary:              $purple-500 !default;
$brand-info:                 $cyan-500 !default;
$brand-success:              $green-500 !default;
$brand-warning:              $orange-500 !default;
$brand-danger:               $red-500 !default;
$brand-rose:                 $pink-500 !default;
$brand-inverse:              $black-color !default;
```

I do understand the roles of primary, info, success, warning and danger as it matched the theme colors of the bootstrap.

My questions are:
1) what is semantical meaning of $brand-rose color?
is it what bootstrap4 calls secondary? (Tbh it looks like a specific implementation for a given dashboard example and should be renamed)
2) what is semantical meaning of $brand-inverse color? Inverse to what?
3) what should I do if I have two branding colors? I'm missing $brand-secondary... 
4) and the biggest concern is that looking at your code I see that color system is not extendible. Which means that if I add $brand-secondary or $brand-dark it will not be processed by sass compilation and as the result I will not have extra classes like .card-header-secondary and .card-header-dark. Do you have plans on fixing that?

**Comment by groovemen** [comment]
Hello @Qvatra, 

Thank you for using our products and for your constructive feedback. For now, you can find-replace the variables names that are set by us. In the near future, we will start the update for this product and we will set a new variables name, new structure for SCSS and so on.
Hope that information helps you. Please let us know if we can help you with anything else.

All the best, 
Stefan
