### ISSUE TITLE
datetime picker is not working in Angular

### ISSUE THREAD

**Issue by ghten** [creativetimofficial/ct-material-dashboard-pro#239]
I  use Material Dashboard Pro in angular but not the version for angular and datetimepicker don't work. I don't see the calendar. I see nothing, I use it as the example 
<input type="text" formControlName="birthday" class="form-control datetimepicker">
And I have verified the installation, js and scss are installed.

Thanks

**Comment by groovemen** [comment]
Hello @ghten, 

Thank you for using our products, please let us know if it wasn't easier to work with the Angular version, also I will ask you to send us your order ID.

All the best, 
Stefan
