### ISSUE TITLE
is-focused color - hard to see on small displays

### ISSUE THREAD

**Issue by jtallinger** [creativetimofficial/ct-material-dashboard-pro#243]
Hi,

I have Material dashboard Pro and face an issue with the text color on focus during search. On bigger displays the focus color is grey and that works well on white background, but on smaller displays where search field is moved into the side menu then text is still grey but now on black/dark background.

<img width="493" alt="Screenshot 2019-05-31 at 5 46 02 PM" src="https://user-images.githubusercontent.com/16815730/58697402-07dcf900-83cc-11e9-82f7-b94d7d1840ff.png">
<img width="258" alt="Screenshot 2019-05-31 at 5 46 17 PM" src="https://user-images.githubusercontent.com/16815730/58697403-07dcf900-83cc-11e9-9953-a46ab63d5848.png">

I've been trying to dig around and find a solution but so far come out empty handed. Could do with a bit of advice on this matter? Could two colors be used and change automatically when field is moved into the side menu?

Thanks,

Br, Joakim

**Comment by groovemen** [comment]
Hello @jtallinger,

Thank you for using our products, you can change the color for the cursor on small displays by setting through a @media query the property: `caret-color: red;` for example. 

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
