### ISSUE TITLE
Page Examples - Using longer content breaks the layout

### ISSUE THREAD

**Issue by multiuniversal** [creativetimofficial/ct-material-dashboard-pro#246]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

On Material Dashboard Pro (BS4) examples - I would expect the page to look good if I add more content to it.

# Current Behavior

The content goes on top of the top navigation and background image stops repeating after scrolling down. See attached screenshots.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome 75

## Failure Logs
![CT-FailBottom](https://user-images.githubusercontent.com/15019499/60098638-ae63b200-975e-11e9-892b-20a26906d122.png)
![CT-FailTop](https://user-images.githubusercontent.com/15019499/60098639-aefc4880-975e-11e9-88b8-80555bfa68a2.png)

**Comment by groovemen** [comment]
Hello @multiuniversal, 

Thank you for using our products, here is a quick solution to this problem that you encountered; by setting the following properties to **.card-signup** 
```
    height: 70vh;
    overflow: scroll;
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by multiuniversal** [comment]
Thanks, it would be good to be able to do proper content pages for example in the pricing page I want to do an overview of features side by side so people can compare, this requires a lot more space and scrolling, which is not doable through any of the example templates.

Hope you guys can add an example that works for regular content pages.

**Comment by groovemen** [comment]
Hello again, 

I will talk with my colleagues to propose this idea and we will prepare for the next update a page that fits your requirements. We created these pages to fit the screen, by having 100vh height. 

Cheers, 
Stefan
