### ISSUE TITLE
[Feature Request] Form multiple select cannot responsive

### ISSUE THREAD

**Issue by indradio** [creativetimofficial/ct-material-dashboard-pro#247]
### What is your enhancement?
Form multiple select cannot responsive with many data input, i hope a view like a form tags but we can choose data with dropdown.

**Comment by groovemen** [comment]
Hello @indradio, 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
