### ISSUE TITLE
How to use fullcalendar in material-dashboard

### ISSUE THREAD

**Issue by farhanali2325** [creativetimofficial/ct-material-dashboard-pro#253]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download material Dasboard
2. Download Fullcalendar and include css and js files
3. Calendar show but click is not working on any date. Popup modal is not going to open.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System: Windows 10 
* Browser and Version: Chrome and Firefox

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @farhanali2325, 

Thank you for using our products, I will ask you to give us your orderID to make a verification. If you are using the PRO version (https://demos.creative-tim.com/material-dashboard-pro/examples/calendar.html), it works just fine. 

All the best, 
Stefan
