### ISSUE TITLE
Modal not blocking body's scroll

### ISSUE THREAD

**Issue by Izuzvo** [creativetimofficial/ct-material-dashboard-pro#256]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

### # Expected Behavior

Hi there. I am expecting that whenever a modal is open, the scroll of the body is blocked as it is told in the Docs:

[https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/components/modal.html#usage](https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/components/modal.html#usage)

**# Current Behavior**

What happens is that even with the modal open (and the body with the class ".modal-open") the full page is scrollable.

This doesn't affect the modal directly as it stays fixed in its position, but having the body moving all over in the background when using the scroll is something I don't want for the UX.

**## Context**

* Device: Desktop 
* Operating System: Windows 10
* Browser and Version: 77.0.3865.90 (Official Build) (32-bit)

Thanks in advance!

**Comment by groovemen** [comment]
Hello @Izuzvo, 

Thank you for using our products, all you have to do is to set the class ps-child into the modal: <div class="modal ps-child">. You could find the fix right here: https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/plugins/perfect-scrollbar.html

All the best,
Stefan

**Comment by ArianulIslam** [comment]
This problem occurred for .perfect-scrollbar-on class in html tag. To solve this problem find & 
open material-dashboard.js file and comment out the $('html').addClass('perfect-scrollbar-on'); 
or change the class name to 'perfect-scrollbar-off' 
Don't forget to update the js version material-dashboard.js?v=2.1.2 to new version material-dashboard.js?v=2.1.3 to reset javascript version on your browser.
