### ISSUE TITLE
CSS bug on mini sidebar

### ISSUE THREAD

**Issue by doqimi** [creativetimofficial/ct-material-dashboard-pro#257]
It looks like an horizontal scrollbar is shown in Chrome if you use the mini sidebar, is there a patch or fix available? 

Issue is present on your hosted demo page as well.

![Screenshot](https://user-images.githubusercontent.com/57569898/68532468-216f5e80-02e3-11ea-8c81-75d8d017a7f7.png)

**Comment by groovemen** [comment]
Hello @doqimi, 

Thank you for your interest in working with our products.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well. Also, please let us know about your OS and browser version.

All the best,
Stefan

**Comment by doqimi** [comment]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When minimized I shouldn't see an horizontal scrollbar at the bottom of the sidebar.

# Current Behavior

What is the current behavior?

When using the mimized sidebar it shows a vertical scrollbar at the bottom the of the sidebar.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html
2. Click on the Cog at the right side of the screen
3. Enable sidebar mini
4. Look at the bottom of the mini sidebar you'll now see a vertical scrollbar

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10 
* Browser and Version: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

## Failure Logs

N/A

**Comment by groovemen** [comment]
Hello again @doqimi,

We have tested this page on Windows 10 on Chrome and Microsoft Edge and it looks good. 

![MDPro](https://user-images.githubusercontent.com/21063398/68676903-ad8fb900-0563-11ea-8e70-4053c580e3df.png)

Please check if you have errors in the console. It should look good because you can find the perfectScrollbar plugin in the product.

Waiting for your answer. 
Best, 
Stefan

**Comment by doqimi** [comment]
See attached, the issue persists in multiple browsers. (big red arrow pointing down)

![2019-11-23 08_20_02-](https://user-images.githubusercontent.com/57569898/69480158-82f6f900-0dca-11ea-917e-79c482abdae0.png)
![2019-11-23 08_20_22-Window](https://user-images.githubusercontent.com/57569898/69480159-82f6f900-0dca-11ea-98cd-9652e0dc2808.png)

**Comment by DavidKettler** [comment]
It looks like the overflow is set to auto. These two solutions got rid of the scroll bar for me.
`
.sidebar-wrapper {
    overflow: hidden !important;
}
`
or
`
.sidebar-wrapper::-webkit-scrollbar {
    display: none; 
}
`

**Comment by immesys** [comment]
Confirming this issue is still present

**Comment by groovemen** [comment]
Hello @immesys,

Thank you for using our products, for now, the solution of @DavidKettler is a quick and good one. Please set the property from above and it will work. We will also solve into the next update this issue. Sorry for this inconvenience. 

All the best, 
Stefan
