### ISSUE TITLE
Double scroll bar on minimized screen

### ISSUE THREAD

**Issue by devildog3261** [creativetimofficial/ct-material-dashboard-pro#258]
Double scrollbar when less than 991px width. happens on most pages, especially pricing and register pages.

![Capture1](https://user-images.githubusercontent.com/55672860/69003520-94736900-08d1-11ea-8636-5209dcb8db91.JPG)
![Capture2](https://user-images.githubusercontent.com/55672860/69003525-abb25680-08d1-11ea-92c9-9f8bb87b766c.JPG)

**Comment by groovemen** [comment]
Hello @devildog3261,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
