### ISSUE TITLE
Calendar CSS - weekly and daily - white header labels on white background

### ISSUE THREAD

**Issue by piotrpawluk** [creativetimofficial/ct-material-dashboard-pro#260]
Calendar:
In the light theme days numbers are white on the white background. It can be seen on the live demo.

Expected behavior: days numbers visible

**Comment by groovemen** [comment]
Hello @piotrpawluk, 

Thank you for using our products, please provide us more details about your issue. We checked the live preview and it's working just fine:
<img width="1388" alt="Screenshot 2020-01-16 at 10 25 23" src="https://user-images.githubusercontent.com/21063398/72506492-a7aba200-384a-11ea-94e3-15d6f2c61570.png">

Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best, 
Stefan

**Comment by piotrpawluk** [comment]
change the calenar view to week or day. In the month view it is ok.
<img width="1183" alt="Zrzut ekranu 2020-01-16 23 23 17" src="https://user-images.githubusercontent.com/10399081/72567915-335b1800-38b7-11ea-8aea-b9dc1687fc33.png">

**Comment by groovemen** [comment]
<img width="1151" alt="Screenshot 2020-01-17 at 10 30 34" src="https://user-images.githubusercontent.com/21063398/72596349-8c0cce00-3914-11ea-894f-da3cd25c754c.png">

Also on week/day it looks good. As we asked you, please fill the ISSUE_TEMPLATE or we will close this issue. We need more details about your project/environment for example, the version of your product, your OS and so on.

Best, 
Stefan

**Comment by piotrpawluk** [comment]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

visible days numbers in v-calendar (week and day view)

# Current Behavior

The numbers are white with the white background

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Calendar component
2. choose week view

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MacBook Pro 
* Operating System: OSX 10.15.2
* Browser and Version: Safari 13.0.4, Google Chrome 79.0.3945.130 

## Failure Logs
--

**Comment by groovemen** [comment]
We checked in the downloadable archive and also on the livePreview and it looks good. Please download again the product because the issue could be from your project. 

<img width="1206" alt="Screenshot 2020-01-20 at 10 42 36" src="https://user-images.githubusercontent.com/21063398/72711525-e191e680-3b71-11ea-8548-3d51272c5fff.png">

All the best, 
Stefan
