### ISSUE TITLE
Gulp Compile and Serve not working on extracted ct-material dash

### ISSUE THREAD

**Issue by edwardtilley** [creativetimofficial/ct-material-dashboard-pro#265]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

gulp serve - should simply host the Material PRO template so I confirm that all is working before adding my flask implementation

# Current Behavior

gulp is throwing errors

# Failure Information (for bugs)

getting a ton of errors on gulp compile and gulp serve

$ gulp compile-scss
assert.js:374
throw err;
^
AssertionError [ERR_ASSERTION]: Task function must be specified
at Gulp.set [as _setTask] (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\node_modules\←[4mundertaker←[24m\lib\set-task.js:10:3)
at Gulp.task (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\node_modules\←[4mundertaker←[24m\lib\task.js:13:8)
at Object. (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\gulpfile.js:34:6)
←[90m at Module._compile (internal/modules/cjs/loader.js:955:30)←[39m
←[90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)←[39m
←[90m at Module.load (internal/modules/cjs/loader.js:811:32)←[39m
←[90m at Function.Module._load (internal/modules/cjs/loader.js:723:14)←[39m
←[90m at Module.require (internal/modules/cjs/loader.js:848:19)←[39m
←[90m at require (internal/modules/cjs/helpers.js:74:18)←[39m
at execute (C:\Users\etilley\AppData\Roaming\npm\node_modules\←[4mgulp-cli←[24m\lib\versioned^4.0.0\index.js:36:18) {
generatedMessage: ←[33mfalse←[39m,
code: ←[32m'ERR_ASSERTION'←[39m,
actual: ←[33mfalse←[39m,
expected: ←[33mtrue←[39m,
operator: ←[32m'=='←[39m
}
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

I went to the trouble of ensuring I was running gulp v4.0.0 on Windows 8.1 dev machine by using these commands per https://hackersandslackers.com/upgrading-to-gulp-4/

1. npm install gulp-cli -g
2. npm install gulp@4.0.0 -D
3. these compiles asked for updates of 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System:  Windows 8.1
* Browser and Version:  Chrome 
* installing by cmd terminal on Visual SC

"devDependencies": {
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^4.1.0",
    "gulp-clean": "^0.3.2",
    "gulp-install": "^1.1.0",
    "gulp-open": "^2.1.0",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.6.3",
    "minimatch": "^3.0.4"
  },
  "dependencies": {
    "graceful-fs": "^4.2.3",
    "material-dashboard": "^2.1.0"
  }

## Failure Logs

Please include any relevant log snippets or files here.  See Above ...

**Comment by groovemen** [comment]
Hello @edwardtilley,

Thank you for using our products, the problem is from gulpfile.js and package.json. Please overwrite the files attached below into your project: 
[gulpfile.js.zip](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/4224009/gulpfile.js.zip)
[package.json.zip](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/4224010/package.json.zip)
and after that run `npm install `and `gulp open-app` in order to run the local server

All the best, 
Stefan

**Comment by edwardtilley** [comment]
Worked like a charm - Thanks Stefan

**Comment by edwardtilley** [comment]
Stefan - when I make changes to the template, what command do I use to update the minified files?

**Comment by groovemen** [comment]
Hello again @edwardtilley,

Unfortunately, we don't have any command that updates the minified files. There are online tools that minify the file that you upload:
https://cssminifier.com/
https://csscompressor.com/
https://www.minifier.org/
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by edwardtilley** [comment]
Thanks for this Stefan - I didn't see your response until just now. I just created an issue because I have a use case where "watch" and minify would be a help.

**Comment by groovemen** [comment]
Hello again, 

Thank you for your interest in working with our products, the watch command is working fine in our product if you want to integrate the minifier, you have to run this command when you finished all the changes. Here is a helpful link showing how you can set the CSS minify: https://medium.com/devux/minifying-your-css-js-html-files-using-gulp-2113d7fcbd16
Hope that information helps you.
All the best, 
Stefan
