### ISSUE TITLE
I want to change date format on datepicker input below from m/d/y to d/m/y.

### ISSUE THREAD

**Issue by nexusnx** [creativetimofficial/ct-material-dashboard-pro#266]
`<input class="form-control datepicker" id="prazo" type="text" required name="prazo">`

**Comment by nexusnx** [comment]
And translate it to pt-br i looked for an awnser in old issues around the github, stack or google. But all of solutions does not work for me.

**Comment by groovemen** [comment]
Hello @nexusnx,

Thank you for using our products, all you have to do is to set the date format (d/m/y) when you initialize the picker: 
```
$('.datepicker').datepicker({
    format: 'mm/dd/yyyy'
})
```
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
