### ISSUE TITLE
TypeError: $(...).perfectScrollbar is not a function

### ISSUE THREAD

**Issue by zellers** [creativetimofficial/ct-material-dashboard-pro#270]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

This applies to my project but also to the Demo @ https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html

On Windows: minimizeSidebar button should minimize the Sidebar. 

# Current Behavior

On Windows: minimizeSidebar button does not minimize the Sidebar. Console shows: `TypeError: $(...).perfectScrollbar is not a function`

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Goto https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html **ON WINDOWS**.
2. Click the minimizeSidebar button
3. Check console in developer tools. See error `TypeError: $(...).perfectScrollbar is not a function`

## Context

* Device (a): MacBook Pro (Retina, 13-inch, Late 2013)
* Operating System (a): Windows 10 Pro Version 1903 (OS Build 18362.592)
* Browser and Version (a.a): Google Chrome 80.0.3987.132
* Browser and Version (a.b): Firefox 74.0 (64-Bit)

* Device (b): VMWare Fusion
* Operating System (b): Windows 7 Ultimate Version 6.1 (Build 7601: Service Pack 1)
* Browser and Version (b.a): Google Chrome 80.0.3987.132
* Browser and Version (b.b): Firefox 74.0 (64-Bit)

## Failure Logs

`TypeError: $(...).perfectScrollbar is not a function`

**Comment by groovemen** [comment]
Hello there,

Thank you for using our products and for letting us know about this issue. Until we fix this into the next update, we will ask you to make the following changes:

 go to assets/js/material-dashboard.js and delete function from line 18 to 29
 paste this function instead:
(function() {
  isWindows = navigator.platform.indexOf('Win') > -1 ? true : false;

  if (isWindows) {
    // if we are on windows OS we activate the perfectScrollbar function
    var ps = new PerfectScrollbar('.sidebar');
    var ps1 = new PerfectScrollbar('.sidebar-wrapper');
    var ps2 = new PerfectScrollbar('.main-panel');
    var ps3 = new PerfectScrollbar('.main');
    $('html').addClass('perfect-scrollbar-on');

  } else {
    $('html').addClass('perfect-scrollbar-off');
  }
})();
Sorry for this inconvenience and hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
