### ISSUE TITLE
Selectpicker issue

### ISSUE THREAD

**Issue by sanket29395** [creativetimofficial/ct-material-dashboard-pro#273]
![Annotation 2020-03-25 171953](https://user-images.githubusercontent.com/44260521/77533587-27926000-6ebd-11ea-9355-5ffc6ec82117.png)

selectpicker dropdown position not set properly when it's above div's height is greater than around 600px.

**Comment by groovemen** [comment]
Hello there @sanket29395,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
