### ISSUE TITLE
Sibar Mini not working on Material Dashboard Pro v2.1.2

### ISSUE THREAD

**Issue by Neo149** [creativetimofficial/ct-material-dashboard-pro#274]
![Capture](https://user-images.githubusercontent.com/11661294/78460549-07834d80-76c2-11ea-9640-6294fab5c875.JPG)

**Comment by NeoRamohlokoane** [comment]
Sidebar Mini not working

**Comment by groovemen** [comment]
Hello @Neo149,

Thank you for using our products and for letting us know about this issue, we will solve it into the next update. Until then, we'll ask you to delete the old initialization for `perfectScrollbar` and the sidebar will work properly. 

<img width="1663" alt="Screenshot 2020-04-06 at 11 47 21" src="https://user-images.githubusercontent.com/21063398/78540163-68af3c00-77fc-11ea-97f2-0edf0bd7ba76.png">

Your if statement should look like in the example below, so please change in your project in `examples/dashboard.html` at line 1117:
 ```
 if (md.misc.sidebar_mini_active == true) {
  $('body').removeClass('sidebar-mini');
  md.misc.sidebar_mini_active = false;

  if ($(".sidebar").length != 0) {
    var ps = new PerfectScrollbar('.sidebar');
  }
  if ($(".sidebar-wrapper").length != 0) {
    var ps1 = new PerfectScrollbar('.sidebar-wrapper');
  }
  if ($(".main-panel").length != 0) {
    var ps2 = new PerfectScrollbar('.main-panel');
  }
  if ($(".main").length != 0) {
    var ps3 = new PerfectScrollbar('main');
  }
  $('html').addClass('perfect-scrollbar-on');
} else {
  $('html').addClass('perfect-scrollbar-off');

  ps = null;

  setTimeout(function() {
    $('body').addClass('sidebar-mini');

    md.misc.sidebar_mini_active = true;
  }, 300);
}
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by Neo149** [comment]
Thank you.
