### ISSUE TITLE
Premium Support charged but NOBODY EVER GIVE SUPPORT in +3 month!

### ISSUE THREAD

**Issue by floripaoliver** [creativetimofficial/ct-material-dashboard-pro#282]
I am really upset about your support! You charge premium support and months nobody ever reply anything or give any support. I cant recommend working with you to anybody! You can delete this post but since there is no other way to get ever listened to or contact your team I used this place to blow off some steam!

thank you!

**Comment by groovemen** [comment]
Hello @floripaoliver,

Thank you for your interest in working with our products, please point us to your unanswered issue and we will solve it right away. We're sorry to hear that from one of our customers but I think we could have solved this problem in another way. 

All the best, 
Stefan

**Comment by floripaoliver** [comment]
Hi Stefan, thank you for your reply,

Sorry for writing in github about my disappointment but I got really upset
that I actually bought premium support 4 month ago but I never received any
support. Your products are high grate and top of the line but you really
need to give at least the premium customer support, otherwise this is just
not making sense. I would have already bought 3 or 4 times a product from
your guys but since I never get any feedback I gave up.

Below you can see my original question plus (one of the ticket numbers)
from my tries to get some little help from you guys.
Please let me know HOW and WHERE I can support if needed? I am willing to
always pay PREMIUM support or even the double for your products IF there is
some basic support available in case needed.

Thank you for helping me now anyways...(below my problem)
Oliver

====================================================================
Your request (12629)

Hi there, I have an issue with my Menu Sidebar. For some reason the
scrollbar finishes only below the fold and if I scroll the menu down the
last option is below the fold. I can't scroll any further.
I checked a couple of times the DIVs and construction but can't figure it
out. In your Demo it works fine so I somehow miss something.I would be
happy if you can help me out with that.

I uploaded the images to explain further.

My Problem here: https://ibb.co/Prgtc1y
Correct from your Demo would be this: https://ibb.co/58qS4Vy

I can also provide you with a login to my developer version
https://jdl.internet-arts.com (this is the entire domain, no .com etc.)
username: office@internet-arts.com
Password: 123123123

Just login and then make the screen (browser window) smaller than the menu
would be visible.
Then the scrollbar is below the end of the screen (fold). in your demo this
works perfect.

Thank you for your support in advance,
Oliver Kuchendorf

======================================================================================

**Comment by floripaoliver** [comment]
Again 3 days passed, again no help?

**Comment by groovemen** [comment]
Hello @floripaoliver, 

We don't work at weekends so that's why it past 3 days. Please use the following link to create a new issue:
https://www.creative-tim.com/new-issue/material-dashboard-pro 
Cheers, 
Stefan

**Comment by floripaoliver** [comment]
I am really starting to give up. After 4 month sending emails, asking for
support, paying premium support you send me a link to create a support
ticket!
*BUT the system is not working*, I add all information, add my *ORDER ID
(according to your own invoice) *and get the error message that the ID is
invalid!
I cant send the support request because my order number is invalid but IS
CORRECT!

I attached 3 screenshots for your reference.
My invoice is also attached.

How is somebody supposed to get support from you?
4 month have passed for something simple! Please let me know how I can get
the support I paid for from a product I paid for.

My issue:
======================
I have a issue with my Menu Sidebar. For some reason the scrollbar finishes
only below the fold and if I scroll the menu down the last option is below
the fold. I can't scroll any further. I checked a couple of times the DIVs
and construction but cant figure it out. In your Demo it works fine so I
somehow miss something

I uploaded to images to explain further.

I can also provide you with a login to my developer version

URL: jdl.internet-arts.com
USERNAME: office@internet-arts.com
Password: 123123123

Just login and then make the screen (browser window) smaller than the menu
would be visible.
Then the scrollbar is below the end of the screen (fold). In your demo this
works perfect.

The scrollbar should be visible and the menu is scrollable until the end so
you see the last option. Correct from your Demo would be this:
https://ibb.co/58qS4Vy
My Problem here: https://ibb.co/Prgtc1y The scrollbar seems to end below
the fold and the end is not visible. the last menu item is not even visible
anymore.

thx
regards
Oliver Kuchendorf

**Comment by groovemen** [comment]
Hello Oliver, 

Thank you for using our products, we're sorry to hear that you are so disappointed. Here is what you have to do to solve this issue: 
- you have added a logo that is bigger than what we have on the demo so the whole sidebar has been pushed down so you need to change the height property of the **sidebar-wrapper** class. 
 `  height: calc(100vh - 250px);` - this is an example

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by floripaoliver** [comment]
Thank you so much, this solved it perfectly. Just for the future reference,
how do I get support? Where I have to write? I still have about 8 month
Premium left.

**Comment by groovemen** [comment]
Hello,

Our usual way to open an issue is to follow this link and fill that form: https://www.creative-tim.com/new-issue/material-dashboard-pro but it's weird that you said you cannot make it. Please send us the email with which you made the purchase to investigate what's happening. 
Also, you can contact us via email or Zendesk for further questions.

Regards, 
Stefan

**Comment by floripaoliver** [comment]
I tried like 10 times but your new-issue form does not accept my order ID.

Invoice No: BV43953148
Date: February 25, 2020
Order No: 115135599
Paid with 2CH

You can close this ticket here please but contact me via email ok@internet-arts.com to figure out why I cant send any tickets with my order ID. thx in advance
