### ISSUE TITLE
Problem Scrollbar Sidebar

### ISSUE THREAD

**Issue by ronaldomoura30** [creativetimofficial/ct-material-dashboard-pro#283]
I did tests and I believe this problem is: screen resolution. 

**I tested it in 1366x768 resolution and presented this error:**
![Error_scroll_bar_creative-tim](https://user-images.githubusercontent.com/6032846/87114459-088ac480-c247-11ea-9188-83e533f437f7.png)

![Error_scroll_bar_creative-tim_2](https://user-images.githubusercontent.com/6032846/87114465-0d4f7880-c247-11ea-8264-15a8ac31b7d1.png)

**I tested it in 1920x1080 resolution and presented this error:**
![scroll_bar_creative-tim_1920x1980](https://user-images.githubusercontent.com/6032846/87114591-599ab880-c247-11ea-8a08-e75c9662d94c.png)

**Propose solution:** I believe that this scroll should be customized according to the user's screen resolution.

**Comment by ronaldomoura30** [comment]
Open a ticket on github and it was closed automatically, on your website https://www.creative-tim.com/contact-us, it is not clear how to open a ticket. I am directed to a less explanatory page, with a form: Your order ID *, I do not have this and it does not allow uploading an image.

Its support is not practical, it is not explanatory and the automatic closing of the issue on the github discourages the desire to remain your customer.

**Comment by groovemen** [comment]
Hello @ronaldomoura30,

Thank you for using our products, we are sorry to hear that! I will talk with my colleagues to find a way to be more explanatory or we will make a video tutorial to show how to open an issue on Github. 
Related to your problem, please check the **Perfect Scrollbar** plugin and make sure that it is initialized right: https://mdbootstrap.com/freebies/perfect-scrollbar/?utm_source=GitHub&utm_medium=PerfectScrollbar#howtouse. It should not be related to screen size.
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by floripaoliver** [comment]
I have the same issue and try since 4 month to get support even with PREMIUM SUPPORT. Please guys, really! Please give your PREMIUM customer some option to actually get support and you will sell the double of your already great products. but honestly the support is = zero.
