### ISSUE TITLE
[Bug] material-dashboard-pro HTML v2.1.2 responsive bug

### ISSUE THREAD

**Issue by olivierpons** [creativetimofficial/ct-material-dashboard-pro#288]
### Version
2.1.2
### Reproduction link
https://no-link-required.com/
### Operating System
Linux
### Device
PC
### Browser & Version
Latest version (2020-10-08)
### Steps to reproduce
- Open the page material-dashboard-pro-html-v2.1.2/examples/forms/extended.html
- Resize it a bit
- you'll see a problem with the "Customisable Select": it's (at some time) not responsive.
### What is expected?
Be responsive all time whatever the width of the browser
### What is actually happening?
The "Customisable Select" fields are some time *not* responsive = ugly visual

---
### Solution
I have none! I need one!

**Comment by olivierpons** [comment]
I need something like the 2 fields of the "Customisable select":
- to have a "type of phone" + a text field "phone"
- to have a "type of address" + a text field "address".

I suppose there are many times where you need a select option + an input next to it, so this resize / responsive problem might be important...

**Comment by groovemen** [comment]
Hello @olivierpons,

Thank you for using our products and for letting us know about this issue. Until the next product update, a quick solution would be to change the following styling code: 
```
.bootstrap-select:not([class*=col-]):not([class*=form-control]):not(.input-group-btn) {
    width: 220px;
}
```
with the following:
```
.bootstrap-select:not([class*=col-]):not([class*=form-control]):not(.input-group-btn) {
    max-width: 220px;
}
```
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
