### ISSUE TITLE
Sweet alert 

### ISSUE THREAD

**Issue by aqeelahmedqs** [creativetimofficial/ct-material-dashboard-pro#29]
Hi, i have just purchased this beautiful template.  But there is some query regarding sweet alert.

How to call sweet alert from code behind via c# asp.net.

**Comment by guidevnet** [comment]
This depends on whether you are using WebForms or MVC. Which one are you using?

**Comment by aqeelahmedqs** [comment]
Web forms

**Comment by guidevnet** [comment]
Try this:
```
string sweetAlertConfig = "swal('Good job!', 'You clicked the button!', 'success')";
ScriptManager.RegisterStartupScript(this, this.GetType(), "Pop", sweetAlertConfig, true);
```
