### ISSUE TITLE
[Bug] Buy Now

### ISSUE THREAD

**Issue by lexphx** [creativetimofficial/ct-material-dashboard-pro#297]
### Version
Latest
### Reproduction link
http://kvwpresenze.azurewebsites.net/public/profile
### Operating System
Linux
### Device
Azure
### Browser & Version
Chromium 90
### Steps to reproduce
1. Buy Material Dashboard PRO Laravel. 
2. Install and login.
### What is expected?
No Buy Now button.
### What is actually happening?
Buy Now suggesting to buy the product again.

---

**Comment by teamupdivision** [comment]
Hello and thanks for using Creative Tim products.

The buy button is just part of the demo code, you can remove it from this file resources/views/layouts/navbars/navs/auth.blade.php

All the best

**Comment by lexphx** [comment]
Hello,

Thanks, I have a couple of more questions. For instance how can I add additional fields to the profile (phone, address, etc.) ?

All the Best,
Lex

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
