### ISSUE TITLE
[Bug] login captcha won't work

### ISSUE THREAD

**Issue by lexphx** [creativetimofficial/ct-material-dashboard-pro#299]
### Version
Latest
### Reproduction link
http://kvwpresenze.azurewebsites.net/public/profile
### Operating System
Linux
### Device
Azure
### Browser & Version
Chromium 90
### Steps to reproduce
1. Following tutorial to add captcha feature:
https://dannyherran.com/2020/11/laravel-recaptcha-v2-middleware/
https://www.positronx.io/laravel-captcha-tutorial-example/

### What is expected?
After successful captcha submission redirection to dashboard.
### What is actually happening?
White screen.

---

**Comment by groovemen** [comment]
Hello @lexphx,

Thank you for using our products, unfortunately, we don't offer custom support. It looks like the Recaptcha is set in the development mode - it should set in production to work.
Also, we partnered with a web/mobile agency which has a lot of experience in custom development so please contact the team here: https://services.creative-tim.com/ and they will come with more details regarding your project.
Please let us know if we can help with any other details.

Best,
Creative Tim Staff

**Comment by lexphx** [comment]
Very insightful. However it doesn't matter if it's production or development. Currently it is set to production with the same result. And it's not custom support, but Customer Support, which I have paid for by buying your product, which does not work they way it should. And I'm not paying for something that should work. You support is a joke.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
