### ISSUE TITLE
Online documentation formatting is broken

### ISSUE THREAD

**Issue by nealdav** [creativetimofficial/ct-material-dashboard-pro#303]
CSS appears to be broken and the sidebar navigation is missing. 

https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/getting-started/introduction.html#

**Comment by groovemen** [comment]
Hello @nealdav,

Thank you for using our products and for letting us know about this issue. We are curently working to fix this issue and we will update this product today. Sorry for this inconvenience. 
Please let us know if we can help you with anything else.

All the best,
Stefan
