### ISSUE TITLE
Charts not sized properly on screen resize

### ISSUE THREAD

**Issue by jdybowski** [creativetimofficial/ct-material-dashboard-pro#32]
Problem exists on Android, iOS, and Chrome on Windows PC, not tested further. One way to reproduce this is to render a screen that has charts (i.e., dashboard, charts) in landscape orientation on tablet then switch to portrait, then back to landscape. Charts will be truncated on the right. This is actually my use case, mobile tablet.
You can also duplicate this using chrome on windows PC either by dragging to size or in developer rendering tools.

Screen shots are from Chrome.

![capture1](https://cloud.githubusercontent.com/assets/1773951/25304176/ee47fbf2-272f-11e7-8b17-2074eb6b3536.PNG)

![capture](https://cloud.githubusercontent.com/assets/1773951/25304121/ba1f8f3a-272e-11e7-92cd-acc33674c6d5.PNG)

**Comment by dragosct10** [comment]
Hi @jdybowski! Thank you for using our product and sorry for the late response. We've checked for this issue and we found a way to fix it. I will update below the file `material-dashboard.js` which is modified and you must to go in `assets/js/material-dashboard.js` and replaced the old one with the new one. Then you must add in your html page at the end of the page where `<script>` tags are located the following code: `<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>`. Hope that will work for you and please let us know if everything is working fine!

[material-dashboard.js.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/955021/material-dashboard.js.zip)



Regards,
Dragos

**Comment by jdybowski** [comment]
Thank you for looking into this. I’m checking it out now.

Thanks,

JD
