### ISSUE TITLE
[Feature Request] Carousel Enhancement

### ISSUE THREAD

**Issue by liemteksun** [creativetimofficial/ct-material-dashboard-pro#321]
### What is your enhancement?
I hope I still get support from you guys - my bug / feature request haven't got any response in over a week

Anyway, I use the new carousel (the Example "Pro") - because the old one (the Example) has a bug (see issue #320), which I haven't heard any response from you guys
https://www.creative-tim.com/learning-lab/bootstrap/carousel/material-dashboard

I used to be able to play video on the old carousel (using material dashboard v 2.1.2) - but the new carousel doesn't seem to support video playback (I can't click on it)

Here is the test code
https://osplit.com/s/material-dashboard-pro-html-v3.0.1/pages/pages/slide.html

Please response when you have time

thanks

**Comment by groovemen** [comment]
Hello @liemteksun,

We're sorry for this late response, related to the issue[ #320](https://github.com/creativetimofficial/ct-material-dashboard-pro/issues/320), we just added in the TODO list for the next product update.

Related to the second issue, you will be able to play video (by clicking) if you set `z-index: 1000` for the `.plyr--video`
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by liemteksun** [comment]
OK, thanks - I'll try this tomorrow

How about issue #317? I'm hoping that this could be fixed as well - because it works on material dashboard v 2.1.2
I'm really hoping that this can be fixed - as switching between input-group-dynamic and input-group-static makes the code less readable

thanks

**Comment by liemteksun** [comment]
I updated my sandbox
https://osplit.com/s/material-dashboard-pro-html-v3.0.1/pages/pages/slide.html

I added (I think that's what you want me to do)
	<style>
	.plyr--video {
		z-index: 1000;
	}
       </style>

It still doesn't work

Can you clarify what exactly I need to do?

thanks

**Comment by groovemen** [comment]
Hello again, 

Please try to recompile the SCSS in case you have set the z-index there (here is how you can do it: https://www.creative-tim.com/learning-lab/bootstrap/build-tools/material-dashboard). 
<img width="324" alt="Screenshot 2021-11-10 at 10 10 53" src="https://user-images.githubusercontent.com/21063398/141074787-2ae13590-3f1e-48f3-9903-0a863bf8fef4.png">

We didn't see the styling applied here and if we set it, the carousel works just fine - you can click on the play button from the video.

Best, 
Stefan

**Comment by liemteksun** [comment]
this works!
thanks
