### ISSUE TITLE
[Bug] Page Not Found

### ISSUE THREAD

**Issue by jealvin** [creativetimofficial/ct-material-dashboard-pro#327]
### Version
3.0.2
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro/pages/ecommerce/overview.html
### Operating System
Windows 10 64bit
### Device
HP
### Browser & Version
Chrome 96.0.4664.45 64bit
### Steps to reproduce
1. pages ecommerce overview not found
### What is expected?
pages ecommerce overview showing
### What is actually happening?
pages ecommerce overview not found

---
### Solution
create page overview

**Comment by groovemen** [comment]
Hello @jealvin,

Thank you for using our products, please let us know if there is any reference for this page or a link to it. You can find this page - Ecommerce/Overview in Soft UI Dashboard Pro.
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by groovemen** [comment]
Hello again, 

We found the link to  in the navbar dropdowns from Authentication pages: ecommerce -> general -> overview. We will fix this issue into the next product update. Thank you for letting us know about this problem.

Regards,
Stefan
