### ISSUE TITLE
Need your advice on the following

### ISSUE THREAD

**Issue by muhfred** [creativetimofficial/ct-material-dashboard-pro#33]
Hello Creative Tim,

Thank you for your awesome product, I'm working with my friend Akram to setup the template on an ASP.NET Core Project, and I want your support or guidance on the following issues:

1- The navigation menu on the Sidebar on the left keeps on closing when navigating from page to page, I want the menu to be kept open highlighting the current page. Please advice on how to resolve this issue, or show me what is the property or show me documentation regarding the navigation menu to be able to keep it opened from page to page, it works fine as expected when I view the template from a browser before applying any template engine to the HTML markup. 

2- I'm using Razor Templating engine, I want to display the title of the current page next to the button the minimizes the nav bar, the thing is that I want to separate the title from the the rest of the Markup that is found on every page, which is in the Layout (Master Page) and I want to be able to set the title on every page, meaning that I don't want to include the same markup on every page in order to set this title.

3- If i'm building the table dynamically using JQuery and Ajax, any css classes doesn't get applied, Like tooltips, or checkbox classes.

Please reply with documentation or walk me through resolving these issues.

Thank you.

**Comment by alexandru-paduraru** [comment]
@muhfred thank you for using our product. I will answer for each item:

1. Are you using the class "sidebar-mini"? Or how do you want to have it open? Can you please share a link with us? Are you talking about the collapse elements and their children? Like the Buttons page from Components? If you want that to be activated we recommend you to either use the classes "in" and verify using the ASP.NET the current route and apply that class to the parent of the element like Buttons, or to implement a javascript like in this example: https://github.com/timcreative/light-bootstrap-dashboard-pro/issues/12 which is checking the URL and is applying the class to the collapse element.

2. I understand, but I cannot see which is the problem? Do you have variables in Razor? So you can have something like `<a class="navbar-brand" href="#/dashboard"> $variable_name </a>`?

3. We've built the product using [Material Bootstrap Design](https://github.com/FezVrasta/bootstrap-material-design) and they recommend to use [Arrive JS](https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support) library for dynamical elements.

Please let us know your status.

Best,
Alex

**Comment by muhfred** [comment]
1. The issue that you referred to is the same which I'm facing, to keep the menu open and active when navigation from page to page, so where exactly I should apply this javaScript.
2. no I don't have variables, I have the layout that contains the header(minimize navbar, search, notifications) the navbar on the right, and the body is applied on different pages, I want to display the title of the page on each on next to the minimize navbar button. How can I achieve when everything common is in the layout, and I want to display different title on every page.
3. I got this on figured out thanks.

**Comment by alexandru-paduraru** [comment]
@muhfred sorry for the late response, don't know how we missed this notification!

1. please add the next code in assets/js/material-dashboard.js

```
$(function(){
    var url = window.location.pathname;  
    var activePage = url.substring(url.lastIndexOf('/')+1);
    $('div.sidebar-wrapper ul.nav li a').each(function(){  
        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);

        if (activePage == currentPage) {
            $(this).parent().addClass('active');
        }
    });
    $('div.sidebar-wrapper ul .collapse ul li a').each(function(){  
        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);

        if (activePage == currentPage) {
            $(this).parent().parent().parent().addClass('in');
        }
    });
})
```

2. I think this will help you: https://bytes.com/topic/asp-net/answers/300117-how-change-pages-title-dynamically you need and ID of that div where is the title, and you change that from your controller. Unfortunately, we don't know how ASP.net is working so we cannot give you an exact answer.

3.  That's great.

Best,
Alex

**Comment by muhfred** [comment]
all issues have been resolved, Than you.
