### ISSUE TITLE
Fails when running npm install

### ISSUE THREAD

**Issue by bash4u** [creativetimofficial/ct-material-dashboard-pro#333]
When I download and extract the project, then run npm install it fails.
The log file is attached.

[2022-02-22T17_33_42_761Z-debug-0.log](https://github.com/creativetimofficial/ct-material-dashboard-pro/files/8119163/2022-02-22T17_33_42_761Z-debug-0.log)

**Comment by groovemen** [comment]
Hello @bash4u,

Thank you for using our product and for letting us know about this issue. We have just updated the product - please check it and let us know if it works well.

All the best, 
Stefan
