### ISSUE TITLE
[Bug] Github repo is missing for BS4 version? 

### ISSUE THREAD

**Issue by nealdav** [creativetimofficial/ct-material-dashboard-pro#338]
### Version
 2.2.2
### Reproduction link
https://github.com/creativetimofficial/ct-material-dashboard-pro
### Operating System
10.15
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
All github links for this theme lead to a newer BS5 theme which is different: https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/getting-started/introduction.html?_ga=2.199535210.570340320.1647275484-1930143984.1645824806

https://github.com/creativetimofficial/ct-material-dashboard-pro

### What is expected?
BS4 theme repo
### What is actually happening?
BS5 theme repo is shown

---

**Comment by groovemen** [comment]
Hello @nealdav,

Thank you for using our products, please check the following link: https://github.com/creativetimofficial/ct-material-dashboard-pro-bs4 
All the best, 
Stefan
