### ISSUE TITLE
[Bug] Text boxes placeholder not getting removed once fields filled

### ISSUE THREAD

**Issue by MatinDeWet** [creativetimofficial/ct-material-dashboard-pro#339]
### Version
3.0.3
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro/pages/authentication/signin/basic.html
### Operating System
Win 10
### Device
Desktop
### Browser & Version
Chrome - 99.0.4844.51
### Steps to reproduce
1. Visit: https://demos.creative-tim.com/material-dashboard-pro/pages/authentication/signin/basic.html
2. Fill input fields partially
### What is expected?
- Placeholders of input fields to be removed once fields start to be filled
### What is actually happening?
- Placeholders of input fields not getting removed, the text of fields not readable

---
### Additional comments
![problem](https://user-images.githubusercontent.com/37707364/158234799-481ee2da-c1b4-4055-b1ff-5b52c47da22b.png)

**Comment by rarestoma** [comment]
Hi @MatinDeWet,

Thank you for working with our products.

Can you please give me the code that you tried so I can test it and see what happens?

I tested it on the live demo (https://demos.creative-tim.com/material-dashboard-pro/pages/authentication/signin/basic.html) and it works fine on my side. 

Can you please also tell me what browser are you using? If you open the console, are there any errors?

Best regards,
Rares

**Comment by andresen007** [comment]
I have a similar problem when data is load to a "edit" page. The label float dont work. I use laravel-livewire and the bug is in chrome/safari.

**Comment by rarestoma** [comment]
Hi @MatinDeWet,

I just found the problem, it comes from the perfectscrollbar tries to initialize the fixed plugin but this component doesn't exist in this page. 

The fix is to add this condition on `assets/js/material-dashboard.js`, starting with line 19:

```
  if(fixedplugin){
    var ps2 = new PerfectScrollbar(fixedplugin);
  }
```

Please let me know if it works.

Best regards, 
Rares

**Comment by rarestoma** [comment]
Hi @andresen007,

Thank you for working with our products.

Can you please try the solution above?

Thank you,
Rares

**Comment by MatinDeWet** [comment]
@rarestoma , Thank you for your help seems to have done the trick!
I also had to create a new min file with the changes.

**Comment by andresen007** [comment]
Hallo

I got the time to test the fix now, but I can't get it to work. 

[www.beta.talmatematik.nu](http://beta.talmatematik.nu/login)

Try to login with wrong password. The email "label" is not floating. And the label still dont float when data is load to a "edit" page.

Best,
Søren

**Comment by andresen007** [comment]
JS-file:
<img width="1009" alt="Skærmbillede 2022-03-21 kl  21 28 01" src="https://user-images.githubusercontent.com/4953888/159358890-aceb88b9-3306-475c-8272-0b6eee3874b0.png">

Input - Edit page (livewire):
<img width="586" alt="Skærmbillede 2022-03-21 kl  21 29 05" src="https://user-images.githubusercontent.com/4953888/159359080-19fd07c9-b576-4988-8094-07a65e20084e.png">

Input - Login page (standard):
<img width="1146" alt="Skærmbillede 2022-03-21 kl  21 30 48" src="https://user-images.githubusercontent.com/4953888/159359231-17fcf112-80c0-4338-97d5-1ef55ef98f18.png">

Thank you for your support.

Best,
Søren

**Comment by andresen007** [comment]
Do you have any suggestions?

Best, 
Søren

**Comment by MatinDeWet** [comment]
Hi, sorry for the late reply, work just has been hectic this week.
The application that I am making with this template is just personal. 
I had a similar problem that you had in a manner, but mine would stay floating even is if was provided with an empty string.
The JS basing the floating attribute on the value attribute if it is there or just an empty value.

I made a change to the JS to look if the value attribute actually has a value in it, not just an empty string, maybe try this?

![image](https://user-images.githubusercontent.com/37707364/160230299-f9d32f42-5146-45bb-9d7f-48399acb08a9.png)


I don't know what you are using to develop, but make sure your field is being filled before page load.

**Comment by andresen007** [comment]
Hey

It is completely alright. I'm just hoping to get a solution to the problem. The change you suggest, dont work. I get the following error in the console:

<img width="1426" alt="Skærmbillede 2022-03-28 kl  10 59 59" src="https://user-images.githubusercontent.com/4953888/160364469-ed182806-5b2d-4c8d-a53b-629a7f458a2b.png">


<img width="932" alt="Skærmbillede 2022-03-28 kl  11 00 15" src="https://user-images.githubusercontent.com/4953888/160364420-41b0d92d-8d1d-443f-9465-966634e22e98.png">

I use Laravel and Livewire. But the login page is only Laravel-blade code.

Thank you for your support, I really hope we find a solution.

Best,
Søren
