### ISSUE TITLE
Radio Button Check

### ISSUE THREAD

**Issue by TheSayantan96** [creativetimofficial/ct-material-dashboard-pro#34]
How do I check which radio button is checked?I have tried 

$(document).ready(function() {
        if ($("#InvoiceYes").attr('checked')) {
            alert("invoice yes");
            $("#taxSection").fadeIn(400);
        }
        else{
            $("#taxSection").fadeOut(100);
        }
    });

But this is not working..data-attribute checked=true doesn't add dynamically.pls give me a jquery solution to check which radio button is selected.

**Comment by alexandru-paduraru** [comment]
@TheSayantan96 please use this code to get the checked value:

`$("input[name='optionsRadios']:checked").val();`

More about checked elements here: http://stackoverflow.com/questions/596351/how-can-i-know-which-radio-button-is-selected-via-jquery

Please let us know if that was working.

Best,
Alex
