### ISSUE TITLE
Nav pills dark version

### ISSUE THREAD

**Issue by hj-w** [creativetimofficial/ct-material-dashboard-pro#356]
Is there a dark version of nav pills?
Under https://demos.creative-tim.com/material-dashboard-pro/pages/pages/profile/overview.html the nav pills are white even in dark mode.

**Comment by groovemen** [comment]
Hello @hj-w,

Thank you for using our products and thank you for letting us know about this issue. We will update this feature into the next product update. 

All the best,
Stefan
