### ISSUE TITLE
datalabels not show up on chartjs pie chart

### ISSUE THREAD

**Issue by abunajmi** [creativetimofficial/ct-material-dashboard-pro#362]
I have the issue when using chart js pie chart, i want to shot the labels of data on pie chart ,  I have rifer the site to access the plugin datalabels but when the template has run the data label not show up on pie chart , please give me solution of that isseu thanks

**Comment by groovemen** [comment]
Hello @abunajmi,

I just answered your other opened issue. 

Cheers,
Stefan

**Comment by abunajmi** [comment]
If I want to show value of data chart on this sample pie chart how to make
it posible , nice if you give me the sample code thanks

Pada tanggal Sen, 22 Mei 2023 15.40, Stefan ***@***.***>
menulis:
