### ISSUE TITLE
[Bug] Font awesome not showing

### ISSUE THREAD

**Issue by Joannick** [creativetimofficial/ct-material-dashboard-pro#378]
### Version
3.0.6
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro/pages/dashboards/analytics.html?_ga=2.116422528.721090067.1694683245-1453533998.1683635642
### Operating System
Windows 10
### Device
Lenovo
### Browser & Version
Google Chrome
### Steps to reproduce
1. Go to : https://demos.creative-tim.com/material-dashboard-pro/pages/dashboards/analytics.html?_ga=2.116422528.721090067.1694683245-1453533998.1683635642
2. Font awesome not showing
3. Error on page checked : GET https://kit.fontawesome.com/42d5adcbca.js net::ERR_ABORTED 403 (Forbidden)
### What is expected?
Font awesome showing
### What is actually happening?
Font awesome not showing

---

**Comment by luckebar** [comment]
Please fix this problem, it doesn't work for anyone anymore

**Comment by Joannick** [comment]
Hi there, support answer me with a good news !
We have to create our own free account on fontawesome website.
Then, you will have a link like this : https://kit.fontawesome.com/12az34er78.js, then replace the old link on your files and it's fixed :)
