### ISSUE TITLE
Radio and Checkbox validation

### ISSUE THREAD

**Issue by noricumbo** [creativetimofficial/ct-material-dashboard-pro#4]
Hi @alexandru-paduraru 

Do you have a radio and checkbox validation workaround? It seems that those type of fields are not covered on the theme documentation.

Thanks!

**Comment by alexandru-paduraru** [comment]
@noricumbo our product was built on the top of (Bootstrap Material Design)[https://github.com/FezVrasta/bootstrap-material-design] and the checkboxes and radios are coming from that UI Kit. At this moment we don't have something tested/implemented so we will check what is the best way of integrating jQuery Validation with the checkboxes and radios and come back with a solution.

Keep in touch,
Alex

**Comment by noricumbo** [comment]
Ok, thank you. I really like you work with inputs validation. I'm struggling a little with radios and checkboxes because they don't react at all when the're required.

I'm implementing a temporary solution but It'll be really helpful that this comes integrated with the theme.

I hope and trust you will integrate a nice solution for this.

Thanks!

**Comment by dragosct10** [comment]
Hi, @noricumbo! We just finished to integrate a solution for your request and in the below code I will explain you the steps that you must follow: 

1. First you need to open validation.html page and put the attribute `required="true"` inside the `<input type="checkbox" />` tag, then go to the line 611 and replace the `$(element).parent('div').addClass('has-error');` with `$(element).closest('div').addClass('has-error');`.
2.Second go to line: 143 in material-dashboard.js and add these lines of code: `    $('input[type="checkbox"][required="true"]').on('click', function(){
        if( $(this).hasClass('error') ){
            $(this).closest('div').removeClass('has-error');
        }
    });
`
3. Third and final step open _checkboxes.scss, go to line: 138 and add these lines of code:
`&.has-error{
      label{
          color: $brand-danger;
      }
  }`

After you put this code you must to compile the SCSS with Koala compiler[(http://koala-app.com/)].

All the best,
Dragos

**Comment by noricumbo** [comment]
Hi @dragosct10!

I have this error in Koala when I add to line 138 the class .has-error:

```
../material-dashboard.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 138 of ../material-dashboard/_checkboxes.scss
        from line 66 of ../material-dashboard.scss
  Use --trace for backtrace.
```

Can you help me with this?

**Comment by dragosct10** [comment]
Hi, @noricumbo! I just uploaded the entire `_checkboxes.scss` partial, please open this document then take all the code from inside and replace with your code from`_checkboxes.scss`, after you will do this you must to compile again with Koala.

Here is attached the `_checkboxes.scss`: 
[_checkboxes.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/638974/_checkboxes.scss.zip)

**Comment by noricumbo** [comment]
Ok @dragosct10, I've tested with checkboxes and it works. Do you have an implementation for radio inputs?

Thanks!

**Comment by dragosct10** [comment]
Yes, if you want validation for radio I will explain in the following code how to implement this:
   1. First you must put the attribute required="true" inside the <input type="radio" /> tag in validation.html page.
   2. Second go to line: 143 in material-dashboard.js and add `input[type="radio"][required="true"]`to this: 
```js
$('input[type="checkbox"][required="true"], input[type="radio"][required="true"]').on('click', function(){
        if( $(this).hasClass('error') ){
            $(this).closest('div').removeClass('has-error');
        }
});
```
    3. Third and last step you have to add the css to `_radios.scss` line 70:
```css
&.has-error{
      label{
          color: $brand-danger;
      }
  }
```

Keep in touch, 
Dragos

**Comment by noricumbo** [comment]
Ok thanks @dragosct10!

It works correctly. Are you adding this to the next release?
