### ISSUE TITLE
SelectPicker does not bind well to the model retrieved via AJAX

### ISSUE THREAD

**Issue by mabernabe** [creativetimofficial/ct-material-dashboard-pro#53]
I use material-dashboard Pro as a Single Page Application. I have a main page with sidebar view and the right frame is loaded with Angular ng-view label and route service. In main page I have this at the bottom:

`<!--  Core JS Files   -->` 
`<script src="assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>` 
`<script src="assets/js/jquery-ui.min.js" type="text/javascript"></script>` 
`<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>` 
`<script src="assets/js/material.min.js" type="text/javascript"></script>` 
`<script src="assets/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>` 
`<!-- Forms Validations Plugin -->` 
`<script src="assets/js/jquery.validate.min.js"></script>` 
`<!--  Charts Plugin -->` 
`<script src="assets/js/chartist.min.js"></script>` 
`<!--  Notifications Plugin    -->` 
`<script src="assets/js/bootstrap-notify.js"></script>` 
`<!-- Vector Map plugin -->` 
`<script src="assets/js/jquery-jvectormap.js"></script>` 
`<!-- Sliders Plugin -->` 
`<script src="assets/js/nouislider.min.js"></script>` 
`<!-- Select Plugin -->` 
`<script src="assets/js/jquery.select-bootstrap.js"></script>` 
`<!-- Sweet Alert 2 plugin -->` 
`<script src="assets/js/sweetalert2.js"></script>` 
`<!-- TagsInput Plugin -->` 
`<script src="assets/js/jquery.tagsinput.js"></script>` 
`<!-- Material Dashboard javascript methods -->` 
`<script src="assets/js/material-dashboard.js"></script>` 
`<script src="js/angular.min.js"></script>` 
`<script src="js/angular-route.js"></script>` 
`<script type="text/javascript" src="js/routes.js"></script>` 

In my right frame, this is my select:

 `                                       <div class="row">`
 `                                           <div class="col-md-12">`
 `                                               <label class="col-sm-2 label-on-left">Channel number</label>`
  `                                              <div class="col-sm-2">`
  `                                                 <select class="selectpicker" data-style="btn btn-primary btn-round"  ng-model="ConfigureWiFiBasicCtrl.configureWiFi.channelNumber">`
  `                                                      <option disabled>Select Channel number</option>`
  `                                                      <option value="1">1</option>`
  `                                                      <option value="2">2</option>`
  `                                                      <option value="3">3</option>`
  `                                                      <option value="4">4</option>`
  `                                                      <option value="5">5</option>`
  `                                                      <option value="6">6</option>`
  `                                                      <option value="7">7</option>`
  `                                                      <option value="8">8</option>`
  `                                                      <option value="9">9</option>`
  `                                                      <option value="10">10</option>`
  `                                                      <option value="11">11</option>`
  `                                                      <option value="AUTO">Auto</option>`
  `                                                  </select>`
                                                   
  `                                              </div>`
  `                                          </div>`
  `                                      </div> `

In my right frame  at the top I have this, otherwise the selectpicker is not even shown:

 `   <!-- Material Dashboard javascript methods --> `
 `<script src="assets/js/material-dashboard.js"></script> `

When the right frame loads, a controller get via API REST the model data. The option selected when the pages load for the rest of the form is right, and sometimes also for the selectpicker is right, but sometimes for the selectpicker is wrong and it shows no option has been selected but I check the REST API is working well. It seems to me it is a timing issue like it depends on some javascript code associated to the selectpicker is loaded before or after the model is retrieved by the controller. So I dont know how I to fix this wrong behaviour.

**Comment by alexandru-paduraru** [comment]
@mabernabe thank you for using our product. Please read this comment to understand better how the SelectPicker is working: https://github.com/creativetimofficial/material-dashboard-pro/issues/51#issuecomment-310341307. Now for your case the activation for the select picker is in material-dashboard.js on line 89: $(".selectpicker").selectpicker(); 

Please try to add the initialisation of the selectpicker on the ngAfterViewInit, or somewhere after the Model is loaded, in this way you make sure it was loaded at the right time. Or you can try to run the selectpicker update/refresh after you added the data from the model, more about this is in the documentation from the comment that I added.

Please let us know your status.

Best,
Alex

**Comment by mabernabe** [comment]
Yes you are right, Thanks. I added this after retrieving data via REST API:
$('.selectpicker').selectpicker();
$('.selectpicker').selectpicker('val', self.configureWiFi.channelNumber);
