### ISSUE TITLE
Styles bug in modal-lg class

### ISSUE THREAD

**Issue by MrJmpl3** [creativetimofficial/ct-material-dashboard-pro#60]
In modal-lg class so bug!

The problem start with the class: modal-lg from Bootstrap

**Comment by alexandru-paduraru** [comment]
@MrJmpl3 thank you for using our product and for pointing that out. Do you have an example that we can check? Any print screens? OS and Browser?

Best,
Alex

**Comment by MrJmpl3** [comment]
- https://github.com/creativetimofficial/material-dashboard-pro/issues/73
