### ISSUE TITLE
Admin mega menu

### ISSUE THREAD

**Issue by cristian-chiric** [creativetimofficial/ct-material-dashboard-pro#63]
Is it possible to add a "vertically mega menu" for admin like magento 2 has in [admin area](http://www.customerparadigm.com/images/Magento/Magento-2.0/Magento-2-Git-Status-Security-Report/Magento-2-Git-Status-Main-Menu-Display.gif)?

Cheers,
Cris

**Comment by alexandru-paduraru** [comment]
@cristian-chiric thank you for using our product and sorry for the late response, we've been on a small vacation. This is the first time when somebody is requesting this. We usually wait for 3-5 requests for a feature before implementing it for all the customers. Till then maybe this will give you a good starting point: https://codepen.io/ajaypatelaj/pen/prHjD

Hope this is ok for you.

Best,
Alex
