### ISSUE TITLE
Font Roboto don't work in Firefox Linux Mint

### ISSUE THREAD

**Issue by NibiruanChild** [creativetimofficial/ct-material-dashboard-pro#64]
Firefox 54.0 (x64) 
Mozilla Firefox for Linux Mint
mint - 1.0

Linux Mint 18.2

![image](https://user-images.githubusercontent.com/1393724/29206728-4a417e18-7e94-11e7-820d-af263df9b3e3.png)

**Comment by alexandru-paduraru** [comment]
@NibiruanChild thank you for showing us the issue. If Roboto is not working, then how there is still some text on the dashboard? That is very weird. Any ideas?

Best,
Alex

**Comment by NibiruanChild** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/31389

2017-08-19 1:20 GMT+04:00 Alex Paduraru <notifications@github.com>:

**Comment by alexandru-paduraru** [comment]
@NibiruanChild thank you for the details. Should we add the Noto Font as the next font after Roboto? As a backup solution?

**Comment by NibiruanChild** [comment]
This is not solution. Firefox detect roboto and try to use.

22 авг. 2017 г. 17:00 пользователь "Alex Paduraru" <notifications@github.com>
написал:
