### ISSUE TITLE
datatabels.net and checkbox not alligned nicely

### ISSUE THREAD

**Issue by KretAZ** [creativetimofficial/ct-material-dashboard-pro#66]
Hi. I have a problem with alligment your beautifull checkbox in datatables.net and in forms.

![image](https://user-images.githubusercontent.com/30315394/29634084-e725c8e8-8848-11e7-932d-95131ad48ce4.png)

My code look like:

![image](https://user-images.githubusercontent.com/30315394/29634299-b09dfc90-8849-11e7-932e-88930cfbe0f5.png)

In documentation examples you are not combining checkbox with other inputs in one row.
In simple table in activity example it looks well.

What am I doing wrong ? :-)

**Comment by dragosct10** [comment]
Hi @KretAZ! Please can you give us a link of your project to be able to fix the problem, because we tried to combine checkboxes with other inputs but it's still working fine.

Regards,
Dragos

**Comment by sbatty** [comment]
Same issue here. Please follow up.
