### ISSUE TITLE
SweetAlert works in IE, but not Material Dashboard Pro's version of SweetAlert2

### ISSUE THREAD

**Issue by hiphigi** [creativetimofficial/ct-material-dashboard-pro#69]
Easily replicated by trying to go to Components > Sweet Alert on the Material Dashboard Pro preview with Internet Explorer. Tested on versions 8-11.

**Comment by dragosct10** [comment]
Hi @hiphigi! For fixing this you must go in your html page at the bottom of the page and include the following script tag but put the script tag before loading your sweetalert2.js library. Everything should work fine for you after you will do this! 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>`

Regards,
Dragos
