### ISSUE TITLE
Change sidebar background-color

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/ct-material-dashboard-pro#72]
Hi! If you want to change the sidebar background color with another color that it's not used in Material Dashboard Pro you have to follow the steps:

1. First go in `assets/scss/material-dashboard/_variables.scss` and declare your background color variable and the variable for the text of the sidebar. For example:
```css
$red-background-color: #ff0000;
$white-color: #ffffff;
```
2. Go to the project in `assets/scss/material-dsahboard/_sidebar-and-main-panel.scss` and you have to add inside of the class `.sidebar` the following lines of code:
```css
.sidebar{
     &[data-background-color="red"]{
            @include sidebar-background-color($red-background-color, $white-color);
     }
}
```
3. After you do that please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/material-dashboard.css`.

Regards,
Dragos

**Comment by omnecon** [comment]
I have an issue compiling material-dashboard.scss with Koala:

`Error: File to import not found or unreadable: ~bootstrap/scss/bootstrap.
       Load path: /home/phil/wuggl/frontend/src/assets/scss
        on line 21 of /home/phil/wuggl/frontend/src/assets/scss/material-dashboard.scss

16:  *\/
17:  @import "~@angular/material/prebuilt-themes/indigo-pink.css";
18: 
19:  @import "core/variables";
20:  @import "core/mixins";
21:  @import "~bootstrap/scss/bootstrap";`

I admit, I am a newbe to this, but I would appreciate any hints how to get this running. THX!

**Comment by dragosct10** [comment]
Hi, @omnecon! Thank you for using our product. Please, can you tell why did you use that `~` when you import the scss partials? Regards, Dragos

**Comment by omnecon** [comment]
Hi @dragosct10 , thanks for your quick response. 
As I am just trying to change the color of the nav-bar, I followed your instructions from above. I did not change any of the other code yet. I downloaded the latest version of the Material Dashboard PRO [2.0.0] - 2018-03-26. The instruction: @import "~bootstrap/scss/bootstrap"; is in material-dashboard.scss. Do you mean, this does not belong there?

**Comment by dragosct10** [comment]
Hi, @omnecon! I just thought that you put that sign there, it belongs there no problem:D. Please, tell me if you use the latest version of the Material Dashboard `v2.0.1`? Regards, Dragos

**Comment by omnecon** [comment]
I am using Material Dashboard Pro Angular 2 [2.0.0] which was released a few days ago at the 2018-03-26. I have no access to another version.

There you find line 21, which does not compile with Koala:
.../material-dashboard-pro-angular-v2.0.0/src/assets/scss/material-dashboard.scss:
   19   @import "core/variables";
   20   @import "core/mixins";
   21:  @import "~bootstrap/scss/bootstrap";
   22   @import "core/reboot";

**Comment by chelaruc** [comment]
@omnecon You don't need to compile the scss files with Koala, if you change some code in scss, the product will auto-compile it. Tell me if you need more informations. 
Best, Ciprian
