### ISSUE TITLE
Bug in style : Modal-lg

### ISSUE THREAD

**Issue by MrJmpl3** [creativetimofficial/ct-material-dashboard-pro#73]
When i used modal-lg , the modal style dont work ..

Image: https://imgur.com/a/533M7

**Comment by dragosct10** [comment]
Hi, @MrJmpl3 ! Please, can you tell us which version of MD PRO do you have? 

Regards,
Dragos

**Comment by MrJmpl3** [comment]
Material Dashboard Pro 1.2.0 - HTML Version

**Comment by dragosct10** [comment]
Hi, @MrJmpl3! Can you give us the link of your project to check what happened there because in the latest update `1.2.0` we fixed the problem with the modals? We tested the product on Windows on Firefox, Chrome, IE and we didn't have any problems with the modals.

Regards,
Dragos

**Comment by MrJmpl3** [comment]
I use the code from bootstrap and add some inputs

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      Here the form and inputs

    </div>
  </div>
</div>

**Comment by MrJmpl3** [comment]
Update! I edit some SASS File and work in laptop screen .. I dont test in mobile

You have:
`@media (min-width: 992px)
.modal-lg {
    width: 900px;
}`

Replace to:
`@media (min-width: 992px)
.modal-lg {
    width: 100%;
}`

And 
`@media (min-width: 768px)
.modal-dialog {
    width: 600px;
    margin: 30px auto;
}`

Replace:
`@media (min-width: 768px)
.modal-dialog {
    width: 900px;
    margin: 30px auto;
}`

Remember this tested in laptop screen and solved the bug with the class "modal-lg" ..
