### ISSUE TITLE
Fixed Top Menu and different side menu for each Top menu item choosen

### ISSUE THREAD

**Issue by touqeerm** [creativetimofficial/ct-material-dashboard-pro#74]
Hi Creative Team,
I'm using material dashboard pro and  have created a fixed top menu. I need a separate side menu for each Top menu item choosen. Ex: The Top Menu has Operations, Revenue,etc.. When I choose Operations I need a different Sidebar with components listed sample as in the dashboard. I have seen that we specify the list and the items are loaded from the list for sidebar. How can we accomplish in having separate sidebar items. Please assist.

**Comment by alexandru-paduraru** [comment]
@touqeerm thank you for using our product. Can you please send us a link with the webapp? Sincerely, I didn't really understand how that should look. After that, I will have a look with my colleague @dragosct10 and see how we can help.

Best,
Alex
