### ISSUE TITLE
Full Calendar on mobile, i pad and tablet with no click event

### ISSUE THREAD

**Issue by nullplex** [creativetimofficial/ct-material-dashboard-pro#76]
Hi,
I am not getting events in full calendar like click and open popup is not working on mobile and table view? Also its not properly responsive some days are getting outside the boundary. Its working fine on laptop and desktop but when we check on mobile, i Pad or even responsive mode of browser I can get popup on clicking on full calendar date. Please give the solution as soon as possible.

![calendar](https://user-images.githubusercontent.com/29448978/31379656-8a60244c-adcc-11e7-8c14-1a8a0344c17e.PNG)

Thank you.

**Comment by nullplex** [comment]
Please give the solution at the earliest. Thank you.

**Comment by alexandru-paduraru** [comment]
@nullplex sorry for the late response, we will have a look today and come back with a solution. 

Best,
Alex

**Comment by nullplex** [comment]
Thanks @alexandru-paduraru  waiting for the solution.

**Comment by dragosct10** [comment]
Hi, @nullplex! Please, can you tell me which version of Material Dashboard Pro do you have? 

Regards,
Dragos

**Comment by nullplex** [comment]
Hi @dragosct10 
We have Folder with name "material-dashboard-pro-html-v1.1.0" purchased from your main site.
Thank you.

**Comment by dragosct10** [comment]
Hi, @nullplex! Please, can you take the latest version of the product which is `1.2.1`, because in this version the plugins were updated and I think the fullcalendar will work properly? 

Regards,
Dragos

**Comment by nullplex** [comment]
Hi @dragosct10 ,

Please send the updated CSS or JS of the template 1.2.1. Kindly share the link to download or send the files with instructions on mayur.lohite@nullplex.com

Thank you for the followup.

**Comment by nullplex** [comment]
Hello @dragosct10 
I just downloaded the new updated template from your website  dashboard but seems like the issue steel persists. PFA.
We are added a Bootstrap modal Popup on click of any date in full calendar. It is only working on desktop and laptop and not even on responsive view of browser fo ripad and mobile. I tested your raw template as well but same issue with your alert as well.

Kindly check and let us know.
Thank you. 

![image](https://user-images.githubusercontent.com/29448978/33473290-cc673a4a-d69b-11e7-8f40-d8bf3df1f9e5.png)

**Comment by dragosct10** [comment]
Hi, @nullplex! For us in responsive mode, everything is working fine. The alert that we selected to show on the click on any data from the calendar it appears clearly, but you have to put your finger on the screen and try to stay with the finger pressed a few seconds and I think it will work for you too. 

Regards,
Dragos

**Comment by nullplex** [comment]
Hi, @dragosct10 

Can you please show in responsive mode of browser? Because In version 1.2.1 I am not able to get any thing on clicking on any date. I tried multiple combinations but nothing working. here it is.

Thank you.

![image](https://user-images.githubusercontent.com/29448978/33552427-da8dce50-d91a-11e7-97f4-2a5068bc9736.png)

**Comment by dragosct10** [comment]
Hi, @nullplex! I made for you a video to see in responsive mode how it works on our side. Please check this [link](https://www.dropbox.com/s/4ltk0nyl2msxcte/md-pro-fullcalendar.mov?dl=0).

Regards,
Dragos

**Comment by nullplex** [comment]
Hi, @dragosct10 !

I have recorded a video for your online template link and the one I have downloaded which is same. Kindly [check here](https://drive.google.com/file/d/1ehEFH03hf8atCB-JgRKGu4YnvNKr6EL4/view?usp=sharing)

**Comment by dragosct10** [comment]
Hi, @nullplex! if you will stay with the click pointer a little more time when you click the date from the calendar you will notice that the date will focus with a light blue color background and after this, the popup will appear. 

Regards,
Dragos

**Comment by nullplex** [comment]
Hi @dragosct10 !
Still not getting popup on a very long 5-7 second click hold.
I got something here you should try this: click on any date and then click on any left or right arrow next to Month, Week, Day button. You will get a popup.
![image](https://user-images.githubusercontent.com/29448978/33609010-71578480-d9ec-11e7-92bb-01d179a3e07d.png)


I think its a bug of not getting a clickble area properly in mobile and tablet view. Let me know once you try this.

Thank you.

**Comment by nullplex** [comment]
Any progress? Is it fixed?

**Comment by msankitaag** [comment]
Hi I am facing the same issue, things are fine in desktop but in mobiles the click is not triggered, so no popup is visible
