### ISSUE TITLE
Left Side Bar Collapsed Issues

### ISSUE THREAD

**Issue by nullplex** [creativetimofficial/ct-material-dashboard-pro#79]
Hello,
When I collapsed the sidebar from nav bar top and if I have too many <LI> items in side bar the scroll is not properly working and the color never repeat till the end.

PFA

![image](https://user-images.githubusercontent.com/29448978/32327008-f7e1961e-bffa-11e7-9ea5-a0720576aa94.png)

**Comment by nullplex** [comment]
Any Update on this? Need urgent solution for it.

**Comment by nullplex** [comment]
Hi @alexandru-paduraru I would appreciate if you could check this css issue as well.

Thank you.

**Comment by nullplex** [comment]
Hi @dragosct10 ,
I would appreciate if you could check this issue. I guess its not that complex for you to check in CSS only.
Thank you.

**Comment by dragosct10** [comment]
Hi, @nullplex! Sorry for the late response. Please download the latest version of material dashboard and there you will find a new sidebar mini and it will work fine.

Regards,
Dragos

**Comment by nullplex** [comment]
Hi, @dragosct10 !
This issue has been resolved we have replaced all the files with latest version.
Thank you for the help.
