### ISSUE TITLE
TypeError in main scss file

### ISSUE THREAD

**Issue by MrJmpl3** [creativetimofficial/ct-material-dashboard-pro#90]
Hi! I report new bug when compile the sass files in the line 90

Material Dashboard Pro - Developer Edition without Photoshop files - Version 1.2.1

in material-dashboard.sccs has
`@import "material-dashboard/rtl";
"material-dashboard/responsive";
@import "material-dashboard/rtl";`

but the correct is:

`@import "material-dashboard/rtl";
@import "material-dashboard/responsive";`

Another bug in rlt.scss:
Has:
`-webkit-transform: translatX(25px);`
`-webkit-transform: translat3d(0, 0, 0);`

but the correct is:

`-webkit-transform: translateX(25px);`
`-webkit-transform: translate3d(0, 0, 0);`

**Comment by dragosct10** [comment]
Hi, @MrJmpl3! Thank you for your observation. These issues will be repaired in the next update.  

Regards,
Dragos
