### ISSUE TITLE
Material dashboard datatable not working

### ISSUE THREAD

**Issue by gamekvnn** [creativetimofficial/ct-material-dashboard-pro#91]
First, thank you for your bootstrap, it help me alot to create my simple website. When i want to draw a datatables, it not working. I was tried to do every tuts in datatables.net! But it still not working.

i want:
![image](https://user-images.githubusercontent.com/34804347/34324225-06b95fe4-e89d-11e7-9b87-87a7d1c3ca37.png)

but in fact: 

![image](https://user-images.githubusercontent.com/34804347/34324219-bc4cfbf0-e89c-11e7-881b-e3dfe9f541b4.png)

thank you agian!

**Comment by dragosct10** [comment]
Hi, @gamekvnn! Thank you for using our product. Can you tell me if you initialized your table in the scripts because from what I see in the screenshot the datatable it's not initialized? 

Regards,
Dragos
