### ISSUE TITLE
Horizontal scrollbar on datatable not showing in Edge

### ISSUE THREAD

**Issue by DraakKoning** [creativetimofficial/ct-material-dashboard-pro#95]
I have come across a problem with the styling of the datatable where the horizontal scrollbar does not show in Edge. For simplicity sake (and trying to figure out the bug), I took your datatables example for Material Dashboard Pro and added some columns.

Here is the Chrome preview:

![chrome](https://user-images.githubusercontent.com/9840578/34792874-29231b8e-f652-11e7-86ea-4609bf8bdd7c.PNG)

Here is the Edge preview:

![edge](https://user-images.githubusercontent.com/9840578/34792921-4cc4cb46-f652-11e7-886d-527b78eafd84.PNG)

I am not sure if this is a bug or forgot to add something. I have tried to search for the problem, but have not found an exact issue to mine, but most suggested fiddling with sScrollX which did not give me any result. To conclude I will include my code for the table.

Here is the HTML for the table tag part:

```
<div class="material-datatables">
    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
```

And here is the JQuery to initialize the table:

```
$(document).ready(function() {
        var table = $('#datatables').DataTable({
            {#"bJQueryUI": true,#}
        "bStateSave": true,
            "pagingType": "full_numbers",
            "scrollX": true,
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records"
            }

        });

        yadcf.init(table, [
            {
                column_number: 0,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 1,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 2,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 3,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 4,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 5,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 6,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 7,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 8,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 9,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 10,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 11,
                filter_type: "multi_select",
                select_type: 'select2'
            },
            {
                column_number: 12,
                filter_type: "multi_select",
                select_type: 'select2'
            }
        ]);
        $('.card .material-datatables label').addClass('form-group');
});
```

On a side note, I have removed the yadcf plugin code to see if it was part of the problem, but the results were the same. Any help will be appreciated.

**Comment by dragosct10** [comment]
Hi, @DraakKoning! Thank you for using our product and sorry for the late response. Please, can you give us a link to your product exactly with these changes to test and to see what is the problem? 

Regards,
Dragos

**Comment by DraakKoning** [comment]
Hi @dragosct10, thank you for your reply. Unfortunately I cannot show the original website, because of 
 the sensitiveness of the data. I have created the following mock example which has the same issue when opening it in edge: [edge test.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/1634249/edge.test.zip)

I hope this can help. Let me know if I should rather paste the code, if you do not want to download the zip.

Regards
Ryno

**Comment by dragosct10** [comment]
Hi, @DraakKoning! I just tested with your code on windows edge browser and the scroll is working. Please, take a look to this [video](https://www.dropbox.com/s/iy39vmr1zth4idx/IMG_5991.MOV?dl=0). 

Regards,
Dragos

**Comment by DraakKoning** [comment]
Hi @dragosct10, thank you for the video. I see now that the scrolling works. Is there a way to get the scrollbar visible on edge? I tried it on a desktop pc with a normal mice, but I am not able to scroll horizontally.

Thank you,
Ryno
