### ISSUE TITLE
Issue in modal

### ISSUE THREAD

**Issue by alejobh** [creativetimofficial/ct-material-dashboard-pro#99]
Hello, 

Im facing an issue using a modal, when the modal is large and tall, the scroll is focused in the main background, and the content in the modal doesn't scroll down, only pressing the middle button of the mouse to scroll the modal itself

![image](https://user-images.githubusercontent.com/15016271/35069183-7844929c-fba7-11e7-88fc-5656aa376ba4.png)

![image](https://user-images.githubusercontent.com/15016271/35069213-8b138086-fba7-11e7-81c0-ebcef57653ae.png)

**Comment by dragosct10** [comment]
Hi, @alejobh! Thank you for using our product. I put by myself more content in the modal and I tested also on the Mac and Windows and on both platforms everything is working fine. I made for you a video to see what happens on windows with the modal. Please see this [video](https://www.dropbox.com/s/lol2vstsi3agu10/IMG_5995.MOV?dl=0). 

Regards,
Dragos

**Comment by alejobh** [comment]
Hello Dragos,

I've done exactly the same as you do in notifications.html, here is my result in the following link https://drive.google.com/file/d/1GKTFRMk9T5jaTcZkZrJKq0srC2fObf8I/view?usp=sharing

**Comment by dragosct10** [comment]
Hi, @alejobh! Please, can you tell me which version of the product did you use? 

Regards,
Dragos

**Comment by alejobh** [comment]
Hi, @dragosct10 i am currently using v1.2.1

**Comment by dragosct10** [comment]
Hi, @alejobh! Can you give access to your project to see what happened there because it's an annoying situation by our side the things are working good like you saw and inside of your project no? In this way, we can fix the problem. 

Regards,
Dragos
